### ISSUE TITLE
Settings: checkboxes are on top of textfields in a small browser window

### ISSUE THREAD

**Issue by chrismcmahon** [SalesforceFoundation/HEDAP#111]
In a browser window that is small but still a reasonable size, the display of checkboxes and text fields become garbled.  See screen shot.
![screen shot 2015-11-16 at 9 25 41 am](https://cloud.githubusercontent.com/assets/204643/11187577/34e8f148-8c44-11e5-9d45-f7db2d32da17.png)

**Comment by chrismcmahon** [comment]
Also note that the text field for e.g. Primary Business Organization is not long enough to hold the entire string.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by ceiroa** [comment]
@kbromer ~ Does Lurch work for HEDAP?

**Comment by kbromer** [comment]
not yet - we can set it up here though shortly

**Comment by ceiroa** [comment]
Issue was fixed in View mode. We are keeping track if HEDA issues in Agile Accelerator.
