### ISSUE TITLE
HEDA logo for reference in readme

### ISSUE THREAD

**Issue by kbromer** [SalesforceFoundation/HEDAP#122]
![sfdc_heda_rgb](https://cloud.githubusercontent.com/assets/926530/11634976/b4c9814a-9ce1-11e5-98bb-ebd84ce6a0de.png)

**Comment by ceiroa** [comment]
![heda-logo](https://cloud.githubusercontent.com/assets/1894238/13441475/f9c4a81a-dfbc-11e5-847d-0ea36c78210a.png)

**Comment by ceiroa** [comment]
![heda - banner-th5he](https://cloud.githubusercontent.com/assets/1894238/13441500/13d366ec-dfbd-11e5-9df6-d9dee50ce87d.jpg)
