### ISSUE TITLE
Replace master-detail fields with lookups in Affiliation, Program Enrollment, and Course Enrollment

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#153]

**Comment by ceiroa** [comment]
**lurch:attach W-009281

**Comment by ceiroa** [comment]
**lurch: attach W-009281

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001kesAAA" target="_blank">W-009281</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001kesAAA" target="_blank">W-009281</a>

**Comment by ceiroa** [comment]
Closed by #166.

**Comment by mrbelvedere** [comment]
Included in beta release version 1.4 (Beta 2) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 1.4
