### ISSUE TITLE
ADDR_Addresses_TEST2.clearConAddrExisting test method fails with state and country picklists enabled

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#154]

**Comment by ceiroa** [comment]
**lurch: attach W-009283

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001kf2AAA" target="_blank">W-009283</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 1.0 (Beta 5) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 1.4
