### ISSUE TITLE
Add help text to settings page in a similar way to what is done in NPSP

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#155]

**Comment by ceiroa** [comment]
**lurch: attach W-008732

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001hBcAAI" target="_blank">W-008732</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 1.6 (Beta 14) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 1.6
