### ISSUE TITLE
Guarantee data integrity after changing fields from master-detail to lookup

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#157]

**Comment by ceiroa** [comment]
**lurch: attach W-009382

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001x6IAAQ" target="_blank">W-009382</a>

**Comment by ceiroa** [comment]
This item was change to an Investigation in AA, and children items were created for each specific task, such as #169.
