### ISSUE TITLE
Duplicate Affiliation created when primary Affiliation is created

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#159]
If a primary Affiliation to an Account of a type that is in the Affl Mappings settings is created, and additional record gets created as well.

**Comment by ceiroa** [comment]
**lurch: attach W-009326

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001qqgAAA" target="_blank">W-009326</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 1.0 (Beta 5) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 1.4
