### ISSUE TITLE
Add Course and Course Enrollment triggers

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#171]

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000002VzuAAE" target="_blank">W-009459</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 1.6 (Beta 4) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 1.6
