### ISSUE TITLE
If the Account field in a primary Affiliation changes, we will need to clear the old primary field and populate the applicable one

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#175]

**Comment by ceiroa** [comment]
**lurch: attach W-009443

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000029FxAAI" target="_blank">W-009443</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 1.5 (Beta 2) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 1.5
