### ISSUE TITLE
After a primary Affiliation exists, creating a new one of the same type cause two of them to the same Account to be created

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#177]
t also happens if you edit an existing non-primary. Both new Affiliations are created with primary field set to true. 

We recently had a similar (but not identical) issue, and the fix is probably the same. But we should write a test for it too to make sure there are no regressions in the future.

**Comment by ceiroa** [comment]
**lurch: attach W-009486

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000002W54AAE" target="_blank">W-009486</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 1.5 (Beta 3) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 1.5
