### ISSUE TITLE
Logo missing from ApexDocs

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#179]
http://developer.salesforce.org/HEDAP/ApexDocumentation/

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000003b2GAAQ" target="_blank">W-009503</a>

**Comment by ceiroa** [comment]
Change made directly in Github.
