### ISSUE TITLE
Make sure all classes are in the correct ApexDocs group

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#180]
And that they are included in the group's home page.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000003b2LAAQ" target="_blank">W-009504</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 1.6 (Beta 4) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 1.6
