### ISSUE TITLE
Add "Disable Errors" checkbox to System Settings

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#182]

**Comment by ceiroa** [comment]
**lurch: attach W-009417

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001yXHAAY" target="_blank">W-009417</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 1.6 (Beta 14) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 1.6
