### ISSUE TITLE
Change Credits Attempted and Credits Earned fields in Course Enrollment and Program Enrollment to 3,3

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#193]
3 digits on each side of the decimal point.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003OLbUAAW" target="_blank">W-009590</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 1.6 (Beta 14) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 1.6
