### ISSUE TITLE
Seasonal Address Overlap

### ISSUE THREAD

**Issue by patmcqueen** [SalesforceFoundation/HEDAP#196]
Receiving an error "Date ranges for Seasonal Addresses cannot overlap." when in fact no seasonal addresses overlap.  The process to re-create is to:
1) Create a new Contact and let HEDA create the Administrative Account.
2) Create a new Address on the Account that is seasonal
3) Create a second new Address on the account that is seasonal

At this point no matter what the dates are on the second address the seasonality will not work.  The failure seems to be when the second seasonal address is added to the account.  The start times and end times always are seen to overlap.  Attached is a quick video.

This is HEDA 1.5 Installed 3/2/2016 12:17am

[2016-03-14_17-57-13.mp4.zip](https://github.com/SalesforceFoundation/HEDAP/files/172941/2016-03-14_17-57-13.mp4.zip)

**Comment by kbromer** [comment]
Thanks Pat - good find.  FWIW, for your use-case demonstrated (identical dates, y-o-y) you can just leave out the year completely, that will cause the behavior to be enforced based on the dates only, agnostic to the year.  Its actually why we use the separate fields instead of a date field value for it.

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003OLboAAG" target="_blank">W-009595</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 1.6 (Beta 16) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 1.6
