### ISSUE TITLE
NPE on creation of an address when there is a year specified

### ISSUE THREAD

**Issue by patmcqueen** [SalesforceFoundation/HEDAP#197]
Receiving a NPE when saving an address.  Steps to reproduce:

1) Create new Contact and allow HEDA to create the administrative account.
2) Create a new address on the Administrative account with Seasonal Start and End Year
3) NPE Occurs.

The NPE does not occur when:
a) An address is created without a Seasonal year
b) The address with the seasonal year is created AFTER another address is created.

Essentially if the first address created on an administrative account includes a year in the seasonal address fields a NPE is thrown.

Pat

Organization: HEDAPat(00D36000000ZTruEAG)
User: pmcqueen@salesforce.com.hedapat(00536000000v7VXAAY)

Errors:

----------
 Error #1:

Error Type: System.NullPointerException
Error Date: 2016-03-15 14:29:19
Message: "Attempt to de-reference a null object"

Stack Trace:
 Stacktrace available at the time of saving the record - (hed)

**Comment by ceiroa** [comment]
I also got this yesterday when verifying #196.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by ceiroa** [comment]
Stack Trace:
 Stacktrace available at the time of saving the record - Class.ADDR_Addresses_TDTM.verifyAddrSeasonalNoOverlap: line 734, column 1
Class.ADDR_Addresses_TDTM.run: line 159, column 1
Class.TDTM_TriggerHandler.runClass: line 168, column 1
Class.TDTM_TriggerHandler.run: line 94, column 1
Trigger.TDTM_Address: line 34, column 1

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003OLbyAAG" target="_blank">W-009596</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 1.6 (Beta 16) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 1.6
