### ISSUE TITLE
Make GPA in Program Enrollment to Scale 4 and Precision 3

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#198]

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003OLcrAAG" target="_blank">W-009608</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 1.6 (Beta 17) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 1.6
