### ISSUE TITLE
Provide values to Country of Origin picklist

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#201]

**Comment by ceiroa** [comment]
**lurch: attach W-009563

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000000494aAAA" target="_blank">W-009563</a>

**Comment by ceiroa** [comment]
http://www.iso.org/iso/country_codes

**Comment by mrbelvedere** [comment]
Included in beta release version 1.7 (Beta 1) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 1.7
