### ISSUE TITLE
Consistency naming Relationship and Affiliation name field

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#208]
For affiliations we call the Id field “Affiliation Name” and for relationships we call the Id field “Relationship Number” and they are both auto number. Let's be consistent in how we do this. If I could change everything I would call it a “Key” and not an Id, Name or Number.

**Comment by ceiroa** [comment]
**lurch: attach W-009566

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000000494pAAA" target="_blank">W-009566</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 1.7 (Beta 4) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 1.7
