### ISSUE TITLE
HEDA Settings Tab - Error Settings Not Synced

### ISSUE THREAD

**Issue by CowboyDan** [SalesforceFoundation/HEDAP#209]
In the System section of the HEDA Settings Tab, the page does not properly display what has been selected in Custom Settings.

What is seen on the tab:
![image](https://cloud.githubusercontent.com/assets/383860/13859088/022be0ac-ec58-11e5-98c9-75f86aa31fe9.png)

What is shown in Custom Settings
![image](https://cloud.githubusercontent.com/assets/383860/13859170/797ba2d2-ec58-11e5-8920-61ea724ee787.png)

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003ON2nAAG" target="_blank">W-009658</a>

**Comment by ceiroa** [comment]
This seems to be happening with all hierarchy settings in the managed context. fyi, @chrismcmahon.

**Comment by ceiroa** [comment]
Fixed by #211. It seems like a platform bug regarding Hierarchy Settings in a managed context, but the fix was easy (short, to be more accurate).

**Comment by ceiroa** [comment]
@CowboyDan ~ Latest beta can be found at https://mrbelvedere.salesforcefoundation.org/mpinstaller/hed/beta, in case you want to double check all looks good.

**Comment by mrbelvedere** [comment]
Included in beta release version 1.7 (Beta 4) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 1.7
