### ISSUE TITLE
Try removing SYSTEM_AccountType__c field in Account

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#212]
It's possible we can just look at the Account record type.

**Comment by ceiroa** [comment]
**lurch: attach W-009587

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003OLbFAAW" target="_blank">W-009587</a>

**Comment by mrbelvedere** [comment]
Included in beta release version 1.7 (Beta 4) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 1.7
