### ISSUE TITLE
Allow multiple faculty to be associated with a course offering

### ISSUE THREAD

**Issue by jasonbelland** [SalesforceFoundation/HEDAP#213]
https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000D6uj&fId=0D58000002ZuLY0

Interesting feature to consider, allowing the ability to associate multiple faculty to a course offering. This could include, but would not limited to, TA's, tutors, etc. Anyone associated with a course in some capacity beyond enrollment as a student.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by ceiroa** [comment]
One option could be to let each contact (Faculty, TA, etc) have a Course Enrollment record created, and add a Type field (maybe a picklist) that would determine if it's a Student/Faculty/TA.

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003OvqyAAC" target="_blank">W-009675</a>
