### ISSUE TITLE
Allow for Account record type labels to be changed

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#216]
Right now, if the label of the Administrative of the Household Account record types get changed, all the related functionality will not work. This means they are not translatable into other languages.

We should instead just ask the user for the ID of the record type that he wants to use when an Contact is created without a parent Account. Or (even better), display all the Account record types that exist and let them choose. This avoids them having to deal with IDs.

We can also asks for the record types for which they want addresses to work. Or should we just support Address management in all record types? I don't see a reason why not to...

**Comment by ceiroa** [comment]
@kbromer ~ Let me know what you think about this.

**Comment by kbromer** [comment]
Could also support a default Household type as well - which would be useful to have for considering when to apply naming, etc.

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003OvsLAAS" target="_blank">W-009681</a>

**Comment by ceiroa** [comment]
At a higher level, I don't think it matters which record types are in the org. User just want to have functionality A, C, F enabled on record types W, Y, Z.

**Comment by kbromer** [comment]
Exactly!

**Comment by mrbelvedere** [comment]
Included in beta release version 1.7 (Beta 6) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 1.7
