### ISSUE TITLE
Better UI for error notifications recipient

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#217]
We should display a drop-down with values "All Sys Admins", "User", "Chatter Group". If one of the last two are selected, a field with a magnifying glass next to it (to indicate you can do searches) should appear to allow searching for the specific user or chatter group.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003PVVPAA4" target="_blank">W-009731</a>

**Comment by judisohn** [comment]
A request for this: https://powerofus.force.com/0D58000002eq5pg

**Comment by jlantz** [comment]
Included in beta release 1.27 (Beta 4)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.27
