### ISSUE TITLE
The Ability to Customize the Account Naming Setting

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/HEDAP#218]
Hub thread: https://powerofus.force.com/0D58000002atMIl

Description from the existing item in the internal backlog that has now been closed as duplicate: "Allow users to, for example, add the Contact's student ID to the name of the Administrative Account."

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003Q59HAAS" target="_blank">W-009736</a>

**Comment by jacebryan** [comment]
Closing this Issue as it is not related to an Idea.

**Comment by jacebryan** [comment]
Closed #436 as duplicate . Reopening to continue discussion for PUB issue https://powerofus.force.com/hub-ideas/1158

**Comment by jacebryan** [comment]
Power of US Idea Owner: [Jennifer Sanchez](https://powerofus.force.com/_ui/core/userprofile/UserProfilePage?u=00580000009z5kg&tab=sfdc.ProfilePlatformFeed)
[Power of US Idea](https://powerofus.force.com/hub-ideas/1158)

**Enhancement Request**: Whether the default HEDA account model is set to "Administrative" or "Households" it would be very useful to provide the ability to customize the account naming setting. Similar to NPSP, provide a setting within the HEDA settings to be able to specify the account name format. Here is the NPSP documentation for customizing household names: https://powerofus.force.com/articles/Resource/NPSP-Customize-Household-Names#!#nameformat

**Requirements**:

**Ability to customize the the "Administrative" Account name with the following formats:**

- {!LastName} Administrative Account:  The current option for Administrative Accounts.

- {!{!FirstName}} {!LastName} Administrative Account: Generates an Administrative Account name such as “John Smith Administrative Account”.

- {!LastName} ({!{!FirstName}}) Administrative Account: Generates an Administrative Account name such as “Smith (John) Administrative Account”.

- You can also select other and specify your own naming convention.

**Ability to customize the "Household" Account name with the following formats:**

- none: Does not generate a Household Name, leaving it up to the user to assign one.

- {!LastName} Household:  Generates a Household name such as “Smith Household” or “Smith and Jones Household,” depending on the number of Contacts in the Household.

- {!{!FirstName}} {!LastName} Household: Generates a Household name such as “John Smith Household” or “John and Jane Smith Household”.

- {!LastName} ({!{!FirstName}}) Household: Generates a Household name such as “Smith (John) Household”, “Smith (John and Jane) Household” or “Smith (John) and Doe (Jane) Household”.

- {!LastName} Family: Generates a Household name such as “Smith Family” or “Smith and Jones Family”.

- {!{!FirstName}} {!LastName} Family: Generates a Household name such as “John Smith Family” or “John and Jane Smith Family”.

- {!LastName} ({!{!FirstName}}) Family: Generates a household name such as “Smith (John) Family”, “Smith (John and Jane) Family” or “Smith (John) and Doe (Jane) Family”.

- You can also select other and specify your own naming convention.

**Comment by mrbelvedere** [comment]
Included in beta release 1.47 (Beta 4)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.49
