### ISSUE TITLE
Use setting to determine which type of accounts to delete if they have no children

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#219]
Currently we delete them if they are Household or Administrative account and all children have been deleted, but this should be configurable.

**Comment by ceiroa** [comment]
**lurch: attach W-009779

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003QeozAAC" target="_blank">W-009779</a>

**Comment by jlantz** [comment]
Included in beta release version 1.8 (Beta 5) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 1.8
