### ISSUE TITLE
Use setting to determine which type of accounts support seasonal addresses

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#220]
For this and similar functionality we should probably have a method that gets an account record type ID and returns true or false depending on whether functionality is active for that type. Something like: 

public static Boolean isSeasonalAddrActiveForRecType(ID recTypeID)

**Comment by ceiroa** [comment]
**lurch: attach W-009782

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003QepEAAS" target="_blank">W-009782</a>

**Comment by jlantz** [comment]
Included in beta release version 1.8 (Beta 5) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 1.8
