### ISSUE TITLE
Use setting to determine which Accounts need renaming

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#222]
Currently the method needsHHAccountRename in ACCT_IndividualAccounts_TDTM is not called from anywhere. We either remove it or we allow the user to determine, through a setting, which type of accounts will be renamed.

**Comment by ceiroa** [comment]
**lurch: attach W-009781

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003Qep9AAC" target="_blank">W-009781</a>

**Comment by ceiroa** [comment]
@jvarese ~ I'm not going to open a ticket for this one in AA yet, as we don't know what we are going to do with it at this point...

**Comment by jlantz** [comment]
Included in beta release version 1.10 (Beta 3) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 1.10
