### ISSUE TITLE
De-duplicate Household and Administrative tests after #216 changes

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#223]
Many of our tests are duplicate, to cover both the Household and the Administrative Account models. Since we are now going to allow any piece of functionality to be available to any record type, we should not have duplicate tests and instead have tests that verify any functionality works on any record type.

**Comment by ceiroa** [comment]
**lurch: attach W-009783

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003QepJAAS" target="_blank">W-009783</a>

**Comment by mrbelvedere** [comment]
Included in production release version 1.15
