### ISSUE TITLE
Add help text to Affiliations settings

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#225]

**Comment by ceiroa** [comment]
**lurch: attach W-009561

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000000494QAAQ" target="_blank">W-009561</a>

**Comment by jlantz** [comment]
Included in beta release version 1.8 (Beta 5) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 1.8
