### ISSUE TITLE
unnecessary error messages when deleting account

### ISSUE THREAD

**Issue by chrismcmahon** [SalesforceFoundation/HEDAP#227]
In HEDA, navigate to Contacts. 

Create a new Contact "foo", leaving Account blank in order to have the system create a "foo Administrative account" for the Contact. 

Navigate to "foo Administrative Account" and delete the account.  See this error:

Unfortunately, there was a problem. Please try again. If the problem continues, get in touch with your administrator with the error ID shown here and any other related details.Something has gone wrong. Cannot read property 'childNodes' of null. Please try again.

Navigate to Contacts, see this error: 

Unfortunately, there was a problem. Please try again. If the problem continues, get in touch with your administrator with the error ID shown here and any other related details.Something has gone wrong. Cannot read property 'updateColumns' of undefined. Please try again.

Navigate to Accounts. Tab is empty as expected
Navigate to Contacts. Tab is empty as expected.

**Comment by ceiroa** [comment]
This only happens in Lightning Experience, and it's an error coming from the platform, not from the package. 
![screen shot 2016-04-01 at 5 00 55 pm](https://cloud.githubusercontent.com/assets/1894238/14221303/706eacf0-f82b-11e5-96eb-6c899187fb22.png)
