### ISSUE TITLE
Investigate 1.6 push upgrade failures due to STG_CMP_Header

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#228]
Email from system:

-----------

Your push upgrade of "HEDA 1.6.0" has completed with the following results:

143 Succeeded, 49 Failed

For more information, review the full push upgrade details at https://login.salesforce.com/?startURL=%2Fpackaging%2FpushUpgradeJobDetails.apexp%3FapId%3D03336000000DlP2%26packageName%3DHEDA%26reqId%3D0DV360000008OMD

-----------

Errors group by count: http://ci.salesforcefoundation.org/view/HEDAP/job/HEDA_rel_push_production/1/console

48 failed with...
    Error Type = DeployError
    Title = Deployment Failure
    Message = Definition for js://hed.STG_CMP_Header not found
    Details = 0,,,20,AuraDefinitionBundle
    
1 failed with...
    Error Type = IneligibleUpgrade
    Title = Cannot upgrade beta package
    Message = You cannot upgrade a beta package, because developers can make incompatible changes to a package that has been released as a beta. To install a newer version of the package, you must first uninstall the existing version.
    Details = None

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003QexcAAC" target="_blank">W-009843</a>

**Comment by ceiroa** [comment]
Retrying fixes the problem.
