### ISSUE TITLE
New installs via installer won't add default TDTM handlers

### ISSUE THREAD

**Issue by kbromer** [SalesforceFoundation/HEDAP#231]
Here we set the install to load the handlers only if the install is a push or an upgrade, not if its installed from the AppEx or installer: https://github.com/SalesforceFoundation/HEDAP/blob/master/src/classes/STG_InstallScript.cls#L51

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003RqaFAAS" target="_blank">W-009920</a>

**Comment by ceiroa** [comment]
True, but the handler will create all TDTM records when any other type of object is inserted (Account, Contact, etc) if none exist. We were doing that to facilitate writing the tests.
