### ISSUE TITLE
Current TDTM implementation cannot resolve classes in local namespace

### ISSUE THREAD

**Issue by kbromer** [SalesforceFoundation/HEDAP#232]
Per this KB known issue: https://success.salesforce.com/issues_view?id=a1p30000000SVY3AAO

We currently use a the Type.forName call with the single parameter, which does not allow us to extend it outside of hte managed package context with a local class: https://github.com/SalesforceFoundation/HEDAP/blob/master/src/classes/TDTM_TriggerHandler.cls#L142

Ideally, we should try it both ways, once with the local namespace, once without.  Per the two different forName method implementations found here: https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_methods_system_type.htm you can see the 2 param version should be used when inside a managed package context

**Comment by kbromer** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003RqwTAAS" target="_blank">W-009937</a>

**Comment by ceiroa** [comment]
I think we are doing this for classes than implement address validation in Cumulus: https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/STG_PanelADDRVerification_CTRL.cls#L199

**Comment by kbromer** [comment]
Yup, that's the right method implementation. I don't know how it resolves if the namespace is there, i guess just fine since it seems to work for Cumulus... ☁️

**Comment by ceiroa** [comment]
Blog post: http://developer.salesforce.org/#blog/post/2014/11/24/table-driven-trigger-management.html

"Hands-on Training: Extend and Customize the Nonprofit Starter Pack" talk where we used the same example that is in the blog post: https://www.youtube.com/watch?v=nirSO0BQ670

**Comment by kbromer** [comment]
Nope, I'm a moron.  User error.

**Comment by ceiroa** [comment]
The mistake was not making the class **global**, which is something that has happened to other people and is easy to miss.

For reference, if the class was in a third-party package, the class name would need to be stored including the namespace, as in mynamespace.myclass.
