### ISSUE TITLE
"Invalid id: Administrative" error

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#238]
Error received by user when creating a program enrollment record.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000000FdFsAAK" target="_blank">W-010115</a>

**Comment by ceiroa** [comment]
An external user also noticed this: https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000D6uj&fId=0D58000002eq5tx

**Comment by ceiroa** [comment]
Fixed by pushing 1.8 (https://github.com/SalesforceFoundation/HEDAP/releases/tag/rel%2F1.8) to all orgs. The fix was already in the code base, but we needed to rev the version number.
