### ISSUE TITLE
Error notification settings string update

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#239]
We are planning on updating the UI functionality (https://github.com/SalesforceFoundation/HEDAP/issues/217), but in the meantime we should update the string to make it cleared which are the valid values.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000000FdG2AAK" target="_blank">W-010117</a>

**Comment by jlantz** [comment]
Included in beta release version 1.9 (Beta 5) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 1.9
