### ISSUE TITLE
Address Save fails

### ISSUE THREAD

**Issue by chrismcmahon** [SalesforceFoundation/HEDAP#241]
Create a Contact such that an Administrative Account is created for that contact

Go to Addresses and click New

Search for the Account created and click save. 

A notification appears saying (literally) "You created address" but the page underneath the notification shows:

"Looks like there's a problem.
We couldn't find the record you're trying to access. It may have been deleted by another user, or there may have been a system error. Ask your administrator for help."

and no Address record is created.
![screen shot 2016-04-27 at 2 23 46 pm](https://cloud.githubusercontent.com/assets/204643/14868703/cfa7fca0-0c83-11e6-852f-74ee6a779818.png)

![screen shot 2016-04-27 at 2 23 52 pm](https://cloud.githubusercontent.com/assets/204643/14868711/d577bf94-0c83-11e6-9559-1f0e108118fe.png)

**Comment by ceiroa** [comment]
@chrismcmahon Did you test this in Classic? I'd definitely take a look at any issue like this in Classic, to see if it could be a Lightning platform issue. Basically everything in the app should work exactly the same in Classic and LEX.

**Comment by chrismcmahon** [comment]
it fails in Classic also

**Comment by ceiroa** [comment]
I don't see the error message (maybe I'm following a different path), but I do get an error notification when saving a new address:


Error Type: System.NullPointerException
Error Date: 2016-04-27 21:58:28
Message: "Attempt to de-reference a null object"

Stack Trace:
 Stacktrace available at the time of saving the record - Class.ADDR_Addresses_TDTM.verifyAddrAccChildOnly: line 681, column 1
Class.ADDR_Addresses_TDTM.run: line 156, column 1
Class.TDTM_TriggerHandler.runClass: line 168, column 1
Class.TDTM_TriggerHandler.run: line 94, column 1
Trigger.TDTM_Address: line 34, column 1

**Comment by ceiroa** [comment]
**lurch: add

**Comment by daveperry** [comment]
Carlos, I have been trying to recreate this error and have been unsuccessful. It appears to be working as expected. I will keep trying.

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000000FdKEAA0" target="_blank">W-010171</a>

**Comment by ceiroa** [comment]
I was able to replicate after @chrismcmahon showed me the way he was creating addresses. The stack trace is the same:

Error Type: System.NullPointerException
Error Date: 2016-04-27 22:19:31
Message: "Attempt to de-reference a null object"

Stack Trace:
 Stacktrace available at the time of saving the record - Class.ADDR_Addresses_TDTM.verifyAddrAccChildOnly: line 681, column 1
Class.ADDR_Addresses_TDTM.run: line 156, column 1
Class.TDTM_TriggerHandler.runClass: line 168, column 1
Class.TDTM_TriggerHandler.run: line 94, column 1
Trigger.TDTM_Address: line 34, column 1

**Comment by ceiroa** [comment]
Oh, I see what this is. @daveperry, you cannot recreate it because you have something selected in the "Account Types with Multi-Addresses Enabled" setting. You only get the error if nothing is selected.

**Comment by jlantz** [comment]
Included in beta release version 1.9 (Beta 5) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 1.9
