### ISSUE TITLE
Add values to ethnicity field

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#243]
Ethnicity values:
American Indian or Alaska Native; Asian; Black or African American; Hispanic or Latino; Native Hawaiian or Other Pacific Islander; White
 
Based on Common App and CEDS

**Comment by jlantz** [comment]
Included in beta release version 1.9 (Beta 6) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 1.9
