### ISSUE TITLE
Link Contacts and Addesses

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#245]
So Addresses can be seen directly from a Contact's detail view.

**Comment by ceiroa** [comment]
**lurch: attach W-008550

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001gcEAAQ" target="_blank">W-008550</a>

**Comment by mrbelvedere** [comment]
Included in production release version 1.15
