### ISSUE TITLE
creating an Affiliation of Contact type Student with Acad. Prog. marked Primary fails to create Program Enrollment

### ISSUE THREAD

**Issue by chrismcmahon** [SalesforceFoundation/HEDAP#246]
I have been told that when one creates an Affiliation for a Student with an Academic Program marked Primary on the Affiliation record; that a Program Enrollment record representing that Affiliation should be created automatically.  This is not happening: 

Screen shot of Affiliation: 

![screen shot 2016-05-02 at 1 38 17 pm](https://cloud.githubusercontent.com/assets/204643/14967308/86ffc370-106b-11e6-8c89-6e4a09ce5e9c.png)

Account is Academic Program: 

![screen shot 2016-05-02 at 1 39 11 pm](https://cloud.githubusercontent.com/assets/204643/14967312/916c7056-106b-11e6-98af-f390b3e20ea9.png)

No PEs: 

![screen shot 2016-05-02 at 1 39 56 pm](https://cloud.githubusercontent.com/assets/204643/14967324/99864a64-106b-11e6-85bb-20155b72ace7.png)

**Comment by ceiroa** [comment]
The view in the last screenshot is the "Recently Viewed". Check the "See All" view. I just tested this in my org and it seems to work fine...

**Comment by chrismcmahon** [comment]
You're right, I'm wrong. It doesn't show up in the default (Recent) view.
