### ISSUE TITLE
Run all HEDA Lightning Components under LockerService to check if they still work

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#247]

**Comment by ceiroa** [comment]
**lurch: attach W-010011

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003abKfAAI" target="_blank">W-010011</a>

**Comment by jlantz** [comment]
Included in beta release version 1.10 (Beta 1) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 1.10
