### ISSUE TITLE
Add Settings button should be disabled until valid fields exist

### ISSUE THREAD

**Issue by chrismcmahon** [SalesforceFoundation/HEDAP#251]
On the page HEDA/Settings/Relationships/Autocreation (at least)

Create a valid record. Click Add Settings.

Click Add Settings a few more times, as a user might do who failed to notice that their new setting was added.  Nothing seems to happen.

![screen shot 2016-05-11 at 1 33 49 pm](https://cloud.githubusercontent.com/assets/204643/15195592/5c248be0-177d-11e6-8fa0-215dd2caaf20.png)

Click Edit. All the extra clicks of Add Settings have created new invisible records that must now be deleted.

![screen shot 2016-05-11 at 1 35 35 pm](https://cloud.githubusercontent.com/assets/204643/15195600/6135fcae-177d-11e6-9b2a-dc9dcb7a51a7.png)

Suggest that Add Settings button be disabled until content of any of the four text input areas changes

**Comment by judisohn** [comment]
@ceiroa This one doesn't appear to have been pulled in to AA yet?

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003oxx2AAA" target="_blank">W-010534</a>

**Comment by jlantz** [comment]
Included in beta release 1.25 (Beta 1)
