### ISSUE TITLE
Issue with Mailing address states and Military Mailing address codes

### ISSUE THREAD

**Issue by tjb328** [SalesforceFoundation/HEDAP#253]
When importing data, I noticed an issue while trying to import some students who have Military mailing address codes for states as well as some other states such as Puerto Rico. You can find a list of the address codes in the "USPS" codes here:
https://en.wikipedia.org/wiki/List_of_U.S._state_abbreviations

Also this may be out of scope, but numeric two digit state codes for Japan are also an issue. Those codes can be found here:
https://en.wikipedia.org/wiki/ISO_3166-2:JP

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003oKpYAAU" target="_blank">W-010486</a>

**Comment by ceiroa** [comment]
Thanks for letting us know about this, @tjb328.

**Comment by wongmike** [comment]
Hi @tjb328, thanks for the submission. Can you please clarify which field was having the issue? Was it:
Country of Origin
Citizenship

Thanks.

**Comment by tjb328** [comment]
It is for the contacts "State" as part of the "mailing address". Though to correctly fix this, all places where there is a picklist of States, the picklist should include all of the USPS codes.

**Comment by wongmike** [comment]
I'd like to ask a few more questions as it's not quite clear to me why you're seeing the error. The "State" field under "Mailing Address" is a free text field which takes any input, so an import in should not yield any errors. Country of Origin and Citizenship are pick-lists which could be problematic if the countries weren't listed, but I see Puerto Rico in the list. I don't believe we're performing any 2 character checks during import, but will have someone check just in case.

1. Would you be wiling to share an example of one record you had trouble importing?
2. What import method did you use? Was it the import feature under contacts?
3. What file format did you use to import? 
4. Are you in Classic view or Lightning view?

As a longer term solution, we will support a broader range of address codes, but I want to make sure we understand the immediate cause of your error.

Thanks for your help.

**Comment by wongmike** [comment]
Hi @tjb328,

One thought is that you can pre-create the entry using the following steps: https://help.salesforce.com/apex/HTViewHelpDoc?id=admin_state_country_picklists_edit_details.htm&language=en_US

Once the pick-list entires are present, the import should work. This appears to be more core functionality vs. HEDA specific, since we rely on core address functionality.

Please let us know if that works out for you.

**Comment by ceiroa** [comment]
@tjb328 ~ Just to clarify, do you have State and Country Picklists enabled? (https://help.salesforce.com/apex/HTViewHelpDoc?id=admin_state_country_picklists_overview.htm&language=en_US)

**Comment by tjb328** [comment]
Sorry for not responding right away. I was testing this in a sandbox and the error occurred while I was trying to import our data using the Jitterbit Data Loader. I did have picklists enabled and at the time, those values were not present. I have not checked it recently.

**Comment by ceiroa** [comment]
No problem. Thanks for the clarification, @tjb328. Let us know how it goes with @wongmike's suggestions.

**Comment by wongmike** [comment]
@tjb328, just closing the loop on this discussion. It seems like we've got the answer and we hope our suggestions will help improve your next import. Please feel free to reopen this if needed or you can open a new issue as needed.
