### ISSUE TITLE
Remove Household Layout

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#254]
With the updates that allow any piece of functionality (including multi-addresses) to be matched to any Account record type, there is no need any more for different account layouts. 

Removing the HEDA household layout would avoid user confusion.

The installation guide would need to be updated.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003oKpdAAE" target="_blank">W-010487</a>
