### ISSUE TITLE
Adhere to Lightning CLI rules

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#256]
Run Lightning CLI (https://developer.salesforce.com/docs/atlas.en-us.202.0.lightning.meta/lightning/cli_intro.htm) against HEDA.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003oxy5AAA" target="_blank">W-010547</a>

**Comment by jlantz** [comment]
Included in beta release version 1.11 (Beta 1) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 1.11
