### ISSUE TITLE
Enhance Course Enrollment creation flow

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#259]
1. Make Academic Program field in the Course Enrollment layout not required 

2. Automatically populate the Academic Program field when creating a new Course Enrollment (by following Program Enrollment > Academic Program) 

3. Change "Program Enrollment" to "Contact's Program Enrollment" 

4. Change "Academic Program" to "Contact's Academic Program" 

5. Rearrange fields: 

Left: 
Contact 
Course Offering 
Grade 

Right: 
Contact's Academic Program 
Contact's Program Enrollment 
Credits Attempted 
Credits Earned

**Comment by ceiroa** [comment]
**lurch: attach W-010551

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003oxzIAAQ" target="_blank">W-010551</a>

**Comment by jlantz** [comment]
Included in beta release version 1.11 (Beta 2) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 1.11
