### ISSUE TITLE
Tests failures if specific Account record Type is default for profile running tests

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#260]
Parent: #252 

From Hub: 

"The individual accounts test failures occur when the default record type is selected to be one of the HEDA types. Although the instructions (https://powerofus.force.com/articles/Resource/Install-and-Configure-the-Higher-Education-Data-Architecture-HEDA) call for selecting "Adminsistrative" as default, this caused test failures. To work around, I created a new record type (non HEDA) and selected that as the default Account record type for the SysAdmin profile. Suggested code fix: set the account record type to a type which is known to have the behavior testing for. Suggested documentation fix: recommend non-HEDA default record type for profile."

**Comment by ceiroa** [comment]
Shouldn't happen; the tests set their own default record type. Whatever value is stored in the settings shouldn't affect them. @vegad, if you are interested in digging a bit more into this please let us know. It'd be of great help. Otherwise I can take a look at it.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003oy10AAA" target="_blank">W-010571</a>

**Comment by ceiroa** [comment]
Clarification: this is referring to making Administrative the default for the profile, not the default in HEDA Settings.

**Comment by ceiroa** [comment]
Two test fail if Administrative is the default for the profile running the tests:

    ACCT_IndividualAccounts_TEST.deleteContactNormalAccountAdministrativeAcc

    ADDR_Addresses_TES.updateOrgContactToHH

**Comment by ceiroa** [comment]
Also, this only happens if Administrative is the default for the profile. All tests will pass with any other Account record type as the default, no matter if it's part of HEDA or not, except with Business Organization. If Business Organization is selected, test `AFFL_AccRecordType_TEST.addRecordTypeToAcc` will fail, as stated in the comments: https://github.com/SalesforceFoundation/HEDAP/blob/master/src/classes/AFFL_AccRecordType_TEST.cls#L187

**Comment by ceiroa** [comment]
This is related to https://github.com/SalesforceFoundation/HEDAP/issues/279. 

Maybe we should run these tests under a specific user that we create during the test.

**Comment by jlantz** [comment]
Included in beta release 1.15 (Beta 2)

**Comment by mrbelvedere** [comment]
Included in production release version 1.15
