### ISSUE TITLE
Addresses Test Failures

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#261]
Parent: #252

From Hub:

"The Addresses tests failed due to a naming collision between the name of the batch/scheduled job process in the test and the one on the org. When the test ran, it queries the jobs and checks "how many times run". On initial install, this is 0 (test passes this step). Later this test fails as seasonal address update job has been running. The workaround: delete the scheduled job running on the org for seasonal address update. Suggested code fix: query for the exact job in the test."

**Comment by ceiroa** [comment]
Makes sense. We should look into it. Again @vegad, it you are interested in looking into this as well (and maybe even sending a pull request!), we'd be more than happy to help you getting the change in.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003oy11AAA" target="_blank">W-010572</a>

**Comment by ceiroa** [comment]
Cannot reproduce. All addresses tests pass even with the job already scheduled. Which makes sense, since the only test that tries to schedule the job does is through [STG_InstallScript.scheduleJobIfNotScheduled](https://github.com/SalesforceFoundation/HEDAP/blob/master/src/classes/ADDR_Addresses_TEST.cls#L2117), which checks if the job is already scheduled. @vegad, if you have additional info on how to reproduce this issue let us know, and we'll reopen the ticket.
