### ISSUE TITLE
Role-related test failures

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#262]
Parent: #252

From Hub:

The "List has no rows" error was caused by the tests which queried for the 'COO' role on the org. Since my org doesn't have this role, it would return no records and the test would throw an exception. There is an assumption that this role will be present in the org. The workaround: Add the role 'COO' to the org. Suggested code fix: don't assume the 'COO' role is present in the org.

**Comment by ceiroa** [comment]
Replacement code: https://github.com/SalesforceFoundation/Cumulus/blob/dev/src/classes/UTIL_UnitTestData_TEST.cls#L269.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003oy0zAAA" target="_blank">W-010570</a>

**Comment by jlantz** [comment]
Included in beta release version 1.11 (Beta 4) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 1.11
