### ISSUE TITLE
meaningless Course Enrollment for Contact with no Course Offering

### ISSUE THREAD

**Issue by chrismcmahon** [SalesforceFoundation/HEDAP#264]
as of 6 June, on the Create Course Enrollment HEDA page, Contact is a required field but Course Offering is no longer a required field.  See screen shot.

![screen shot 2016-06-06 at 12 30 19 pm](https://cloud.githubusercontent.com/assets/204643/15834996/e5478d0e-2be2-11e6-93c6-165d2069749b.png)

However, the user is allowed to save the record, thus creating a Course Enrollment for a Contact that is completely unconnected to any Course or Course Offering. This seems incorrect. 

![screen shot 2016-06-06 at 12 31 42 pm](https://cloud.githubusercontent.com/assets/204643/15834999/e753e76e-2be2-11e6-876e-e7f369426f76.png)

**Comment by ceiroa** [comment]
Course Enrollment has never been a required field in this layout, but it makes sense to me to make it required. I have just asked Jason Belland about it.

**Comment by chrismcmahon** [comment]
Right, Course Enrollment was not required but there was a different field such that a saved CE record held some meaning. The issue as reported above has no meaning.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003pbevAAA" target="_blank">W-010601</a>

**Comment by jlantz** [comment]
Included in beta release version 1.11 (Beta 3) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 1.11
