### ISSUE TITLE
Support custom objects in TDTM framework

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#267]
Currently, HEDA includes triggers for a number of objects. In this case users that want to add TDTM classes to the framework don't need to create triggers, just the classes. However, users may want to create TDTM classes for objects for which we don't provide triggers, of for custom objects.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003pbgwAAA" target="_blank">W-010624</a>

**Comment by kbromer** [comment]
Thinking about globalizing the factory?

**Comment by ceiroa** [comment]
Yes, a user in the Hub asked about this: https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjxL&fId=0D58000002kgKXC&s1oid=00D00000000hWLM

**Comment by ceiroa** [comment]
UW-Extension also asked about this in the call we had on 6/15/16.

**Comment by CowboyDan** [comment]
Thanks for the updates!

**Comment by mrrigney** [comment]
Hi Carlos, I will certainly plan to take advantage of this as soon as it's available.

**Comment by bovardit** [comment]
+1 on requesting this functionality.  Would be wonderful to have the factory globalized so we can write our own triggers.  Any word on when this will be available?

**Comment by ceiroa** [comment]
It had to be pushed due to competing priorities, but we will start working on this in the current sprint.

**Comment by jlantz** [comment]
Included in beta release 1.19 (Beta 1)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.19
