### ISSUE TITLE
HEDA vs Summer '16: checkbox error

### ISSUE THREAD

**Issue by chrismcmahon** [SalesforceFoundation/HEDAP#268]
All HEDA Settings pages show this error upon loading: 

Something has gone wrong. Error in $A.getCallback() [InvalidStateError: Failed to read the 'selectionStart' property from 'HTMLInputElement': The input element's type ('checkbox') does not support selection.] Failing descriptor: {markup://hed:STG_CMP_Affl}. Please try again.

For Settings that have checkboxes e.g. Relationships, the checkbox cannot be checked 

![screen shot 2016-06-13 at 2 34 50 pm](https://cloud.githubusercontent.com/assets/204643/16024001/60ed231a-3174-11e6-8376-281c9dc515e5.png)

**Comment by davidhabib** [comment]
Chris, you will need to start saying whether you hit these issues with Locker Service enabled or disabled.  If enabled, would also be good to know if you can reproduce it with it disabled.  thanks.

**Comment by chrismcmahon** [comment]
I never approve updates in these test orgs, so assume a pristine un-updated org; locker service is not enabled (until it becomes mandatory in 124 days)

**Comment by daveperry** [comment]
Chris, I created a new org this afternoon and it appears to be working in both classic and lightning - Summer '16.

**Comment by chrismcmahon** [comment]
Then you have Locker Service enabled and my dev env does not: https://developer.salesforce.com/blogs/developer-relations/2016/04/introducing-lockerservice-lightning-components.html

**Comment by daveperry** [comment]
Can you check to see what version you have installed in your sandbox?

**Comment by chrismcmahon** [comment]
v 1.11(beta 4) y'all feel free to poke around in mrbelvedere@heda.browsertests if you'd like

**Comment by ceiroa** [comment]
I logged into that org. LockerService security was activated. I deactivated and the issue goes away. We should still look into it, though.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003qFMYAA2" target="_blank">W-010653</a>

**Comment by ceiroa** [comment]
@chrismcmahon Feel free to activate LockerService security again. It's probably good that the browser tests are catching this issues. In theory, they shouldn't affect lightning components in managed packages until winter16, but better to know about it ahead of time.

**Comment by chrismcmahon** [comment]
What I don't understand about this (and it might be important for docs or support) is that the 'critical update' that activates Locker Service has never been touched and shows as "Not Activated"
![screen shot 2016-06-14 at 8 49 53 am](https://cloud.githubusercontent.com/assets/204643/16049613/384dfb8e-320d-11e6-8dfa-2922625348ab.png)

**Comment by ceiroa** [comment]
It was touched. it got activated. Automatically, I suppose. I DE-activated it. That's why there are no errors now.

**Comment by ceiroa** [comment]
Interestingly, I cannot reproduce the error in unmanaged context.

**Comment by ceiroa** [comment]
It's happening also in the production UAT org, which means all our users are most likely currently affected by this. This is strange, as I thought LockerService security wasn't supposed to apply to existing managed packages.

**Comment by ceiroa** [comment]
I cannot reproduce the error in the gs0 org (with unmanaged code).
