### ISSUE TITLE
 Error messages in HEDA Settings page should be nicely displayed

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#271]
In a user-friendly manner. Now they are just shown as a string at the bottom of the page.

**Comment by ceiroa** [comment]
**lurch: attach W-008614

**Comment by davidhabib** [comment]
Carlos, you can see how I'm doing it in the manage household ui LC here:
https://github.com/SalesforceFoundation/Cumulus/blob/feature/lex-manage-household-REVIEWED/src/aura/HH_Container/HH_ContainerHelper.js#L126

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001gvOAAQ" target="_blank">W-008614</a>

**Comment by ceiroa** [comment]
A user pointed out that an unfriendly error message is displayed at the bottom of the page when you try to create a new reciprocal setting and you don't field the Name field.

![unnamed](https://cloud.githubusercontent.com/assets/1894238/16092836/052e5486-32ff-11e6-903b-3b7c2ff2db4d.jpg)

**Comment by jlantz** [comment]
Included in beta release 1.27 (Beta 2)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.27
