### ISSUE TITLE
Expose the TDTM default config as a global method

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#272]
We do this with our global API in NPSP. We need to do the same so that users writing unit tests can integrated them with our code. The team from UW-Extension just asked about this.

Thread where we talked about how to do this in NPSP:
https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000CjRe&fId=0D58000001xrlVh&s1oid=00D00000000hWLM&OpenCommentForEdit=1&s1nid=0DB800000004Fa7&emkind=chatterPostNotification&s1uid=00580000005vESn&emtm=1426798147229&fromEmail=1&s1ext=0

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003qFPrAAM" target="_blank">W-010670</a>

**Comment by jlantz** [comment]
Included in beta release 1.19 (Beta 1)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.19
