### ISSUE TITLE
 Rename STG_CMP_Header

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#273]
This component causes many failures when doing push upgrades. Every other component is fine. It forces us to re-run the push a number of times.

**Comment by ceiroa** [comment]
**lurch: attach W-010203

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000000FdMPAA0" target="_blank">W-010203</a>
