### ISSUE TITLE
Post-install script stopped running

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#276]
It seems like the post-install script has stopped running. We've noticed this through our browser tests suite, starting on Friday June 17. After a Beta version gets installed in the Beta UAT org, no Affiliation Mappings exist.

No changes to any related code seemed to have been recently done.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003qufrAAA" target="_blank">W-010692</a>

**Comment by ceiroa** [comment]
This does not seem to be happening anymore.
