### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by andyemiller** [SalesforceFoundation/HEDAP#277]
I received an error message upon launching the installer.
 
See the language at the following link: https://www.evernote.com/l/ACOt6detleVJDqkjXdIy1EwOqzcxNCpAIKY
 
Note: This is a safe link to a public comment on my Evernote account. 
 
Any ideas?

**Comment by ceiroa** [comment]
Hi @andyemiller ~ Please post in the HEDA group in the Power of Us Hub (https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000D6uj) and @mention Jason Lantz on it. We mainly use Github issues to track features or bugs that have already been validated. Thanks!
