### ISSUE TITLE
Account record types should not be referenced anywhere

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#279]
Tests should create record types for the duration of each test if appropriate ones don't exist.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003vnS8AAI" target="_blank">W-010740</a>

**Comment by ceiroa** [comment]
Unfortunately, record types cannot be inserted programmatically: https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_dml_non_dml_objects.htm

**Comment by ceiroa** [comment]
@dospromptman ~ Let me know what you are doing around this for NPSP. I worked on what could be the first part of this when I allowed any record type-dependent logic to be chosen for any record type. This came out of #216, and generated #219, #220, and #222.

At that time I centralized all record type queries in https://github.com/SalesforceFoundation/HEDAP/blob/master/src/classes/UTIL_Describe.cls#L454-L477. But we are still hardcoding record type names here. Ideally, I'd like to modify it so that if no record type with that name exists and we are in a test, one gets created for the test. But unfortunately you cannot perform DML on record types. We could instead just get whatever record type exists in the org, put it in the settings and use that, but this doesn't solve the case where there aren't any record types... Let me know if you have a better idea.

**Comment by kbromer** [comment]
Seems like you should be able to grab any record type for the specific sobject in the org (which would implicitly require that there BE a record type at all in the first place), and use that to populate the settings.  That would at least test the record type behavior, which is all we're really after for the most part

**Comment by ceiroa** [comment]
Yes, that's what I meant by " We could instead just get whatever record type exists in the org, put it in the settings and use that, but this doesn't solve the case where there aren't any record types..." :-) It's not ideal, but I guess there's no other option. We actually need at least two record types to exist, since there are tests where we change an account from one type to another.

**Comment by kbromer** [comment]
Yes, I think that's fair - we'll always require at least once since RecordTypeId doesn't exist w/o it 😠
