### ISSUE TITLE
CMP_RecTypes component to check any record types are actually listed

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#280]
If no record types exist or the user does not have access to them, he will receive the following error when trying to save settings:

> Something has gone wrong. Action failed: hed$CMP_RecTypes$controller$saveSettings [TypeError: Cannot read property 'length' of undefined] Failing descriptor: {hed$CMP_RecTypes$controller$saveSettings}. Please try again.

We should check typeCheckboxes variable is not null (checkboxIds has been found in the page), before trying to get the length in https://github.com/SalesforceFoundation/HEDAP/blob/master/src/aura/CMP_RecTypes/CMP_RecTypesHelper.js#L6

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003x6I5AAI" target="_blank">W-010811</a>

**Comment by ceiroa** [comment]
@chrismcmahon @paulmalenke @jlantz The reason why we didn't see this error before in the browser test suite might have to do with the component also being reused for Course Connections. In this case a call to the component may be happening before the save. Just a thought...

**Comment by jlantz** [comment]
Included in beta release 1.19 (Beta 6)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.19
