### ISSUE TITLE
TDTM_Contact: System.LimitException: hed:Too many query rows: 50001

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#281]
As a result of a custom workflow rule, user is getting "TDTM_Contact: System.LimitException: hed:Too many query rows: 50001" error.

Removing AfterUpdate from the "Contact - ACCT_IndividualAccounts_TDTM" Trigger Handler fixes  the problem for the user.

Power of Us Hub thread: https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000D6uj&fId=0D58000002nlZUm

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003x6IAAAY" target="_blank">W-010812</a>

**Comment by ceiroa** [comment]
Initially I thought it might be an infinite loop between the workflow rule and ACCT_IndividualAccounts_TDTM, but I forgot that code will run only once more maximum as a result of a workflow rule, as described in the documentation:

"If the record was updated with workflow field updates, fires before update triggers and after update triggers one more time (and only one more time) [...]"

https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_triggers_order_of_execution.htm

So we'll have to look into what query could be causing this. It'd be helpful to know what the workflow rule is doing, since, as @Kevin Bromer points out, a number of other operations might be happening.

**Comment by ceiroa** [comment]
Closing, as it turned out to be a non-issue:

"Jonathan Maher (Sierra-Cedar)

Looks like the root cause was that the "Standard Account duplicate rule" was activated, blocking creation of identically named Administrative Accounts. This resulted in a large number of Contacts without Administrative Accounts (because the Contact was still inserted, but the IndividualAccounts code was unable to create the Account).

Once this was corrected in Duplicate Management, and the After Update functionality returned to ACCT_IndividualAccounts_TDTM, a bulk update to the orphaned Contacts was able to do exactly what Pat suggested, and create the correct Administrative Accounts.

Following that update, the Workflow Rule was able to be re-activated. I assume that the original error stemmed from repeated attempts to find the correct Administrative Account, and futile attempts to create it."
