### ISSUE TITLE
Course-related label updates

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#282]
Make the following updates, for consistency:

- Rename "Course Offering Name" in Course Offering to "Course Offering ID"
- Rename "Course Offering" in Course Enrollment to "Course Offering ID"
- Rename "Enrollment Number" in Program Enrollment to "Program Enrollment ID"

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003x6KuAAI" target="_blank">W-010819</a>

**Comment by jlantz** [comment]
Included in beta release version 1.12 (Beta 1) and higher

**Comment by mrbelvedere** [comment]
Included in production release version 1.12
