### ISSUE TITLE
Error Handling Modification Implementation

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#284]
Based on conversations on Tuesday 6/28, its been determined we need to modify and narrow the scope of the error handling framework included in the HEDA. A specification outlining a proposed set of error handling use-cases and architectures should be the outcome of this story.

**Comment by ceiroa** [comment]
**lurch:add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003xntaAAA" target="_blank">W-010874</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.31 (Beta 2)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.31
