### ISSUE TITLE
Make Reciprocal Method setting a drop-down

### ISSUE THREAD

**Issue by paulmalenke** [SalesforceFoundation/HEDAP#285]

**Comment by paulmalenke** [comment]
**lurch:attach W-010047

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003abNZAAY" target="_blank">W-010047</a>

**Comment by jlantz** [comment]
Included in beta release version 1.13 (Beta 1) and higher

**Comment by jvarese** [comment]
Hey guys - when does this go "live"?

**Comment by ceiroa** [comment]
It should be pushed to sandboxes on Wednesday, and to production a week after that, if I'm not mistaken. Could you please verify, @cpolcyn? Thanks!

**Comment by cpolcyn** [comment]
This PR resulted in the creation of release beta/1.13-Beta_1. The HEDA 1.13 release will be created on Aug 3 and pushed to sandboxes that evening. It will then be pushed to production the following Tuesday, Aug 9.

**Comment by jvarese** [comment]
Awesome - thank you for this detailed info.

**Comment by mrbelvedere** [comment]
Included in production release version 1.13
