### ISSUE TITLE
Increase test coverage of REL_Utils

### ISSUE THREAD

**Issue by paulmalenke** [SalesforceFoundation/HEDAP#287]

**Comment by paulmalenke** [comment]
**lurch:attach W-008474

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001gB8AAI" target="_blank">W-008474</a>

**Comment by jlantz** [comment]
Included in beta release 1.13 (Beta 4)

**Comment by mrbelvedere** [comment]
Included in production release version 1.13
