### ISSUE TITLE
Implement Course Connections

### ISSUE THREAD

**Issue by paulmalenke** [SalesforceFoundation/HEDAP#289]

**Comment by paulmalenke** [comment]
**lurch:attach W-010931

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003ySybAAE" target="_blank">W-010931</a>

**Comment by jlantz** [comment]
Included in beta release 1.16 (Beta 5)

**Comment by mrbelvedere** [comment]
Included in production release version 1.16
