### ISSUE TITLE
AFFL_AccChange_TDTM and AFFL_ContactChange_TDTM Query in Loop

### ISSUE THREAD

**Issue by kyleschmid** [SalesforceFoundation/HEDAP#290]
Both the AFFL_AccChange_TDTM and AFFL_ContactChange_TDTM classes have a query running in a loop that could easily be moved outside. Line 83 in AFFL_AccChange_TDTM and lines 79 and 83 in AFFL_ContactChange_TDTM.

**Comment by ceiroa** [comment]
Thanks, @kyleschmid. Good catch!

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003g61lAAA" target="_blank">W-011003</a>

**Comment by jlantz** [comment]
Included in beta release 1.16 (Beta 5)

**Comment by mrbelvedere** [comment]
Included in production release version 1.16
