### ISSUE TITLE
COFF_Affiliation_TDTM Deletes Unnecessary Affiliations and Enrollments on Removal of Faculty

### ISSUE THREAD

**Issue by paulmalenke** [SalesforceFoundation/HEDAP#292]
When a Contact is set as Faculty on more than one Course Offering and the Faculty is cleared from one of the Course Offerings, the Faculty is removed as a Course Enrollment from all course offerings that have that Contact as Faculty. Even though the Course Enrollments are removed, that Contact still populates the Faculty field on all of the other Course Offerings. In the case that the original Faculty that created the Affiliation to the parent department is removed, the Affiliation is also removed even if there are other Course Offerings with that Faculty within that department that still warrant an Affiliation.

![enrollafflbug](https://cloud.githubusercontent.com/assets/1997507/17792587/3292c05c-6567-11e6-8a01-6fb4ad14d925.gif)

_note: screencast shows Course Enrollments as Course Connections_

**Comment by paulmalenke** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003gn4kAAA" target="_blank">W-011084</a>

**Comment by jlantz** [comment]
Included in beta release 1.18 (Beta 2)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.18
