### ISSUE TITLE
Label not available in package

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#294]
As mentioned in this Hub thread, label stgHelpHouseholdRecType is not available in package because it isn't referenced in Apex:

https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000D6uj&fId=0D58000002tIbzj

**Comment by jlantz** [comment]
Included in beta release 1.15 (Beta 2)

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003t9YhAAI" target="_blank">W-011090</a>

**Comment by mrbelvedere** [comment]
Included in production release version 1.15
