### ISSUE TITLE
Canada missing in Citizenship and Country of Origin picklists

### ISSUE THREAD

**Issue by patmcqueen** [SalesforceFoundation/HEDAP#296]
Canada seems to be missing from the Citizenship and Country of Origin picklists.

see:  https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000D6uj&fId=0D58000002tIXm6

and search the below:

https://github.com/SalesforceFoundation/HEDAP/blob/8cbd919f523434fa4364f6c1e385232072218b6d/src/objects/Contact.object

**Comment by paulmalenke** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003tp9GAAQ" target="_blank">W-011093</a>

**Comment by jlantz** [comment]
Included in beta release 1.15 (Beta 3)
