### ISSUE TITLE
Drop-down reusable lighning component does not have identifier

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#298]
The rendered drop-down does not include a CSS identifier. It's used in two places right now:

- Default Account Model Setting UI
- Account record type that supports Household Addresses

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003tpA9AAI" target="_blank">W-011103</a>

**Comment by jlantz** [comment]
Included in beta release 1.19 (Beta 5)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.19
