### ISSUE TITLE
Saving seasonal address for Contact error

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#301]
With Contact addresses enabled, if we create a new Address record with seasonal information as child of a Contact we get an error:

Error Type: System.NullPointerException
Error Date: 2016-08-29 21:11:12
Message: "Attempt to de-reference a null object"

Stack Trace:
 Stacktrace available at the time of saving the record - Class.ADDR_Seasonal_UTIL.verifyAddrSeasonalNoOverlap: line 222, column 1
Class.ADDR_Addresses_TDTM.run: line 154, column 1
Class.TDTM_TriggerHandler.runClass: line 167, column 1
Class.TDTM_TriggerHandler.run: line 94, column 1
Class.TDTM_Global_API.run: line 60, column 1
Trigger.TDTM_Address: line 33, column 1

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003uV2mAAE" target="_blank">W-011164</a>

**Comment by jlantz** [comment]
Included in beta release 1.17 (Beta 1)

**Comment by mrbelvedere** [comment]
Included in production release version 1.17
