### ISSUE TITLE
Lightning component that displays all available record types does not have identifiers

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#302]
The checkboxes don't have identifiers, so selenium cannot find them.

We could make these into dropdowns.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003uV3fAAE" target="_blank">W-011175</a>

**Comment by jlantz** [comment]
Included in beta release 1.19 (Beta 3)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.19
