### ISSUE TITLE
Test HEDA in Winter'17

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#317]
Make sure Settings pages work, and there are no issues with our Lightning Components.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000041TJiAAM" target="_blank">W-011317</a>

**Comment by paulmalenke** [comment]
Created #321 to resolve issue found in testing.
