### ISSUE TITLE
Rewrite code that set labels dynamically in settings

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#319]
Messages on empty lists are being set dynamically: https://github.com/SalesforceFoundation/HEDAP/blob/master/src/aura/STG_CMP_Base/STG_CMP_BaseHelper.js#L112-L121.

We shouldn't use $A.get('$Label') and instead use $A.getReference("$Label.c." + labelSubStr), as described in https://developer.salesforce.com/docs/atlas.en-us.202.0.lightning.meta/lightning/labels_dynamic.htm?search_text=dynamic%20labels. We should test 1. that is readily available 2. that only one trip to the server is done to retrieve all labels.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000002w270AAA" target="_blank">W-011360</a>
