### ISSUE TITLE
Settings Account Record Types Checkbox Array Broken in Winter 17

### ISSUE THREAD

**Issue by paulmalenke** [SalesforceFoundation/HEDAP#321]
The Accounts and Contacts settings page displays two separate arrays of Account Record Types and the alignment of those components is broken in Winter 17. Attaching screenshot example.
![heda account checkboxes view](https://cloud.githubusercontent.com/assets/1997507/18929379/d91a600a-8589-11e6-8f2b-69efafc03c6d.png)

**Comment by paulmalenke** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000002xREnAAM" target="_blank">W-011459</a>

**Comment by jlantz** [comment]
Included in beta release 1.19 (Beta 2)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.19
