### ISSUE TITLE
Deploying unmanaged code to org with translation workbench enabled throws error

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#326]
After turning on translation workbench and setting the default language for the organization to Spanish, I run `ant deployWithoutTest` and got a `objects/Address__c.object -- Error: Cannot specify a startsWith attribute for this language` failure. It seems to refer to the `<startsWith>Vowel</startsWith>` element at the bottom of the object definition.

Changing the default organization language back to Spanish, even if the Translation Workbench remains enabled and Spanish active, fixes the issue.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004FvVRAA0" target="_blank">W-017052</a>

**Comment by aligeez** [comment]
Per review with the HEDA Dev team, this is an issue that only pertains to Dev orgs, has no impact on Prod orgs. As such we are closing it.
