### ISSUE TITLE
AFFL_AccRecordType_TDTM not checking for null

### ISSUE THREAD

**Issue by kyleschmid** [SalesforceFoundation/HEDAP#329]
If an Account is changed from a null record type to a non-null record type and doesn't have a primary affiliation mapping for that record type, keyAfflFieldNewType (line 77) is equal to null. This causes an exception when it is added to the query on line 155. This can be fixed by changing line 87 to "} else if (keyAfflFieldNewType != null) {".

**Comment by ceiroa** [comment]
Thank you for this detailed bug report, @kyleschmid. If you are interested in contributing to the project, you could send a pull request with the fix. We'd be more than happy to review and merge it. :-)

**Comment by kyleschmid** [comment]
Just created a pull request.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000048wkYAAQ" target="_blank">W-011653</a>

**Comment by jlantz** [comment]
Included in beta release 1.19 (Beta 4)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.19
