### ISSUE TITLE
User receives HEDA error message when Merging Contacts using DemandTools with Salesforce Merge Disabled

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#332]
We believe this to be a false positive. If so, we should avoid sending this error notification. (We should probably work on this at the same time we redo error handling #284).

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000049ihnAAA" target="_blank">W-011682</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.31 (Beta 2)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.31
