### ISSUE TITLE
Non-default trigger handlers being deleted

### ISSUE THREAD

**Issue by kyleschmid** [SalesforceFoundation/HEDAP#335]
In version 1.19, anytime you create a trigger handler and then perform DML on an object that calls a trigger, that trigger handler is deleted because it is not one of the default trigger handlers in TDTM_DefaultConfig.getDefaultRecords.

**Comment by ceiroa** [comment]
Thanks for reporting this, @kyleschmid. I was able to reproduce the issue and will look into it.

**Comment by kyleschmid** [comment]
I think the issue is in TDTM_Config.getTdtmConfig(). It gets the default config without checking to see if any records already exist in the database.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by jlantz** [comment]
Included in beta release 1.20 (Beta 1)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.20

**Comment by ceiroa** [comment]
**lurch: attach W-015608

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004AWsqAAG" target="_blank">W-016737</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004AWVUAA4" target="_blank">W-015608</a>
