### ISSUE TITLE
Tests fail with country/state picklist enabled

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#338]
The following tests fail with state/country picklists enabled as well as a default value for country:

ADDR_Contact_TEST.noContactToAccPropagation
ADDR_Contact_TEST.noAccToContactPropagation
ADDR_HouseholdAcc_TEST.insertConWithAddrToExistingHH
ADDR_HouseholdAcc_TEST.insertConWithDefaultAddrToExistingHH
ADDR_HouseholdAcc_TEST.insertConWithNoAddrToExistingHH
ADDR_HouseholdAcc_TEST.insertContactWithAddressToHH
ADDR_HouseholdAcc_TEST.insertContactWithMultilineStreetAddressHH
ADDR_HouseholdAcc_TEST.newDupeContactAddrNonDefaultHH
ADDR_HouseholdAcc_TEST.updateConAddrExistingCaseOnlyHH
ADDR_HouseholdAcc_TEST.updateConAddrExistingHH
ADDR_HouseholdAcc_TEST.updateConAddrNewHH
ADDR_Seasonal_TEST.newSeasonalAddrForContact
ADDR_Seasonal_TEST.testSeasonalStartEndYearCurrent
ADDR_Seasonal_TEST.testSeasonalStartEndYearDelete
ADDR_Seasonal_TEST.testSeasonalStartEndYearFromAcc
ADDR_Seasonal_TEST.testSeasonalStartEndYearUpdateDates
ADDR_Seasonal_TEST.testSeasonalStartEndYearUpdateInfo

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004AWyqAAG" target="_blank">W-016782</a>

**Comment by kyleschmid** [comment]
Accidentally included .DS_Store file in the repo. You'll want to remove that from master

**Comment by ceiroa** [comment]
Oh, I see that now. I'll remove it. Thanks for pointing that out.

**Comment by jlantz** [comment]
Included in beta release 1.21 (Beta 3)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.21
