### ISSUE TITLE
Default address not automatically resetting on Seasonal End Dates

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#342]
From https://github.com/SalesforceFoundation/Cumulus/issues/2358

It looks like HEDA is also only querying the start day: https://github.com/SalesforceFoundation/HEDAP/blob/master/src/classes/ADDR_Seasonal_BATCH.cls#L48

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004FvVQAA0" target="_blank">W-017051</a>

**Comment by jlantz** [comment]
Included in beta release 1.24 (Beta 1)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.24
