### ISSUE TITLE
 Investigate adding Personal Email field and Personal option in Preferred drop-down

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#344]

**Comment by ceiroa** [comment]
**lurch: attach W-009668

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003ON3lAAG" target="_blank">W-009668</a>

**Comment by davidjray** [comment]
This item will be closed by #396. That PR makes this a non-issue because with the implementation of #396 System Admins will be able to add custom email fields to a contact and add that custom email label to the Preferred Email picklist.

**Comment by mrbelvedere** [comment]
Included in beta release 1.30 (Beta 6)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.30
