### ISSUE TITLE
Update 'Mailing Address' based on Preferred Address Type

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#345]
From idea in the Hub: https://powerofus.force.com/hub-ideas/1095

This is a lot more complex than phone an email though, due to the multi-address support.

WARNING: we should do https://github.com/SalesforceFoundation/HEDAP/issues/344 first.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004EXzNAAW" target="_blank">W-017028</a>

**Comment by jacebryan** [comment]
@davidjray - WI has been closed (comments on on the WI). Please let me know if there is anything else we need to do with this Issue.

@wongmike
