### ISSUE TITLE
Support relating multiple Courses to multiple Academic Programs

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#349]
Academic Program is an account record type. We recommend making an Academic Program a child of a Department (which is also an account record type).

We recommend making a Course a child of an Academic Department. 

It'd be nice to be able to show that a Course can be part of X,Y, and Z Academic Programs. It'd essentially be a join table from Course to Account.

**Comment by ceiroa** [comment]
**lurch: attach W-008721

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001hAjAAI" target="_blank">W-008721</a>

**Comment by maryannmaguire** [comment]
Please add this feature. Our org wants to link Courses with multiple Academic Programs.

**Comment by aligeez** [comment]
Closing this as a duplicate of #401
