### ISSUE TITLE
testSeasonalStartEndYearFromAcc will fail in January

### ISSUE THREAD

**Issue by kyleschmid** [SalesforceFoundation/HEDAP#353]
testSeasonalStartEndYearFromAcc was failing for me in December. Looks like y'all have updated it for December, but the update will begin to fail in January. I fixed it and will submit a pull request.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004HJfGAAW" target="_blank">W-017156</a>

**Comment by jlantz** [comment]
Included in beta release 1.24 (Beta 5)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.24
