### ISSUE TITLE
Add Dual Citizenship field to HEDA Model

### ISSUE THREAD

**Issue by wongmike** [SalesforceFoundation/HEDAP#360]
The HEDA model currently has a Citizenship field with a picklist of countries. It would be nice to also have a Dual Citizenship field which should also be a picklist of countries.

Link to Power of US Hub Idea here: https://foundation.my.salesforce.com/a1W80000006blHb

Given I am a salesforce user
And I want to add contact details to a contact
When I select edit
Then a Dual Citizenship picklist field is available for me to select a second citizenship status
When I click Save
Then Dual Citizenship value is saved to the contact

**Comment by wongmike** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004PkDNAA0" target="_blank">W-017304</a>
