### ISSUE TITLE
Reentrant flag in CON_PrimaryAffls_TDTM needs to be moved out of loop

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#362]
Reentrant flags are set inside the for loop that starts in line 74:

https://github.com/SalesforceFoundation/HEDAP/blob/b448807f63a7a2f7ecef454ee39358a1c8f7453a/src/classes/CON_PrimaryAffls_TDTM.cls#L93

https://github.com/SalesforceFoundation/HEDAP/blob/b448807f63a7a2f7ecef454ee39358a1c8f7453a/src/classes/CON_PrimaryAffls_TDTM.cls#L133

We should check for the right action first, then loop through the records.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004RBULAA4" target="_blank">W-017315</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.27 (Beta 5)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.27
