### ISSUE TITLE
Unnecessary Query Causing Limit Exception in ACCT_IndividualAccounts_TDTM

### ISSUE THREAD

**Issue by kyleschmid** [SalesforceFoundation/HEDAP#365]
Issue for orgs with close to 50,000 contacts with null AccountId:

1. Contact is inserted with null AccountId
2. ACCT_IndividualAccount_TDTM after insert creates an administrative account and updates contact with new account
3. ACCT_IndividualAccount_TDTM after update adds 'null' to listAccountIdHHToUpdate here: https://github.com/SalesforceFoundation/HEDAP/blob/master/src/classes/ACCT_IndividualAccounts_TDTM.cls#L145
4. All contacts with a null AccountId get queried here: https://github.com/SalesforceFoundation/HEDAP/blob/master/src/classes/ACCT_IndividualAccounts_TDTM.cls#L244

These contacts are unnecessarily queried because they do not have an associated account to update.

I will submit a pull request.

**Comment by kbromer** [comment]
Interesting - I think it would only occur for SysAdmins since that's essentially a private Contact, so a regular user wouldn't see those at all (nor would Apex I think as its closed off via sharing, but alas...)  Fun times, thanks Kyle!

**Comment by kyleschmid** [comment]
No problem. I ran into it today with our Just-in-Time handler for SSO. The handler lets the trigger take care of the admin account creation, so that was causing the error. I imagine we were close to this limit for a while.

**Comment by kbromer** [comment]
Ah, makes sense!

**Comment by jlantz** [comment]
Included in beta release 1.27 (Beta 4)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.27
