### ISSUE TITLE
Custom created email fields do not populate the standard email field once set as preferred in HEDA

### ISSUE THREAD

**Issue by wongmike** [SalesforceFoundation/HEDAP#371]
Currently after creating a custom email field in HEDA, when you manually add the custom email field to the preferred picklist and select the custom email field as preferred, the standard email field is not updated. 

We need the behavior to be when you select any email from the preferred picklist (including custom), that the email will be copied into the standard email field.

**Comment by wongmike** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004bGoXAAU" target="_blank">W-017553</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.30 (Beta 6)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.30
