### ISSUE TITLE
In HEDA, the standard email field can be overwritten with a null value if the preferred email setting points to an empty email field

### ISSUE THREAD

**Issue by wongmike** [SalesforceFoundation/HEDAP#372]
The "Email" field should never be overwritten with a null value. If there is a value in the "Email" field, but there is no address, say, in the "Work Email" field, then, if the "Preferred Email" dropdown is set to "Work" we should not copy the null value from "Work Email" to "Email" (as HEDA currently does); rather, we should display an error "Work Email is null and therefore cannot be preferred"

**Comment by wongmike** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004bGoYAAU" target="_blank">W-017554</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.30 (Beta 6)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.30
