### ISSUE TITLE
Preferred email setting should be required if any email address exists for the contact

### ISSUE THREAD

**Issue by wongmike** [SalesforceFoundation/HEDAP#373]
In HEDA today, if you add an email to the contact, but don't specify any preferred email, then the standard email field will not be populated (assuming the contact's email field wasn't already populated before installation of HEDA). What we'd like HEDA to do is to make the preferred email setting required if and only if there is an email present for a given contact. This must take into account not just the standard HEDA email fields of "University, Work, and Alternate," but also take into account any custom email fields that the admin may have created for their contact.

**Comment by wongmike** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004bGocAAE" target="_blank">W-017555</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.30 (Beta 6)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.30
