### ISSUE TITLE
HEDA should preserve the standard email for a contact by copying that email into the HEDA Alternate Email field

### ISSUE THREAD

**Issue by wongmike** [SalesforceFoundation/HEDAP#374]
Today, if a contact exists prior to the installation of HEDA and that contact has an email address, the salesforce standard email address is hidden from view in the HEDA layout. Moreover, if you then enter in one of the HEDA email address fields: University, Work, Alternate, and set one of them as the preferred email, then that email will overwrite the standard email address.

What we should do is when HEDA is installed, we should check for the presence of an email in the standard email field for each existing contact. If the standard email field is populated, then we should copy the email to the Alternate email field and set the Alternate email field as the preferred email. This will preserve the standard email and also make it the preferred email by default. The admin can change their preferred to another email manually if desired.

**Comment by wongmike** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004bGohAAE" target="_blank">W-017556</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.30 (Beta 6)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.30
