### ISSUE TITLE
Fix help bubble for HEDA > Contact > Alternate Email field

### ISSUE THREAD

**Issue by wongmike** [SalesforceFoundation/HEDAP#377]
Currently the Alternate Email field help bubble says:
"Alternate Email is an optional fourth email: Not personal, preferred, or work email."

This is wrong. Please change it to:

"Alternate Email is an optional email not captured in other email fields."

**Comment by wongmike** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004bGpBAAU" target="_blank">W-017561</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.28 (Beta 4)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.28
