### ISSUE TITLE
Update Administrative Account Name When Contact's Name Changes

### ISSUE THREAD

**Issue by wongmike** [SalesforceFoundation/HEDAP#380]
Link to original Power of Us Hub Idea: [Update Administrative Account Name When Contact's Name Changes](https://foundation.my.salesforce.com/apex/Ideas_Redirect?id=a1W80000006bmfy&sfdc.override=1)

When a contact's name changes, e.g. married name, and changes are made to the contact's last name field, HEDA does not automatically change the name of the associated administrative account. It would be helpful if HEDA could automatically update (similar to NPSP) the contact's related administrative account when there are changes to the last name.

**Comment by wongmike** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004bGtDAAU" target="_blank">W-017574</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.43 (Beta 2)

**Comment by cpolcyn** [comment]
Included in production release rel/1.43
