### ISSUE TITLE
AFFL_AccRecordType_TDTM queries unnecessary contacts

### ISSUE THREAD

**Issue by kyleschmid** [SalesforceFoundation/HEDAP#381]
The method of AFFL_AccRecordType_TDTM queries any contacts whose primary affiliation field is not null for any of the accounts whose old record type had a primary affiliation field mapping. It should only query for contacts related to one of the accounts that have changed. This is a problem when, for example, a business organization account's record type is changed and there's more than 50,000 contacts that have a related business organization in the primary business organization field. Here's the section of code: https://github.com/SalesforceFoundation/HEDAP/blob/master/src/classes/AFFL_AccRecordType_TDTM.cls#L108-L112. I will submit a pull request.

**Comment by mrbelvedere** [comment]
Included in beta release 1.28 (Beta 8)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.28
