### ISSUE TITLE
Expand the Description field in the Course Object to support > 255 characters

### ISSUE THREAD

**Issue by wongmike** [SalesforceFoundation/HEDAP#383]
The current field is limited to 255 characters. Most of the course descriptions for educational institutions are > 255 characters. TES's description field is 7000 characters long, but this seems excessively long. Review of several course catalogs from universities around the country suggests almost all course descriptions are < 1500 characters. 

Make the Description field in the Course Object 2048 characters to account for the vast majority of course descriptions available. > 2048 character descriptions should be truncated or a custom field can be created to support it.

**Comment by wongmike** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004kdY2AAI" target="_blank">W-017581</a>

**Comment by ceiroa** [comment]
If we are going to change the field type, from textarea to long textarea, why not give it the max allowed: 131.072?

**Comment by wongmike** [comment]
My only concern is the amount of space it would consume. I'm all for going for the max size if that's going to be easier. Just to be clear, that's 131,072 characters?

**Comment by davidjray** [comment]
After discussing with @wongmike the decision was made to increase the capacity of the Extended Description field to 131,072 characters.

**Comment by mrbelvedere** [comment]
Included in beta release 1.31 (Beta 1)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.31
