### ISSUE TITLE
some Tooltips for elements in HEDA Create Contact function properly, many do not.

### ISSUE THREAD

**Issue by chrismcmahon** [SalesforceFoundation/HEDAP#387]
Many elements in the HEDA Create Contact screen have tooltip icons. Some of them like Work Phone and Work Email function correctly.  Others like Preferred Phone and Preferred Email do not. (Note that the Tooltip for Work Email says "See Preferred Email", but the Tooltip for Preferred Email does nothing.)

Many examples of both working and non-working Tooltips exist on this page. 

seen in Firefox 50.1 on OSX
![screen shot 2017-01-31 at 1 46 32 pm](https://cloud.githubusercontent.com/assets/204643/22484128/43959018-e7bd-11e6-8ed5-2901b90aaed7.png)

**Comment by chrismcmahon** [comment]
Here is a correct tool tip: 
![screen shot 2017-01-31 at 2 01 19 pm](https://cloud.githubusercontent.com/assets/204643/22487149/7acedcae-e7c9-11e6-81d8-49a7d9ff05c7.png)

**Comment by paulmalenke** [comment]
This is all controlled by the platform and the standard lightning experience. I have searched for a platform bug for this and cannot find one. This is out of our control. This can be closed.
