### ISSUE TITLE
HEDA Settings 'Delete' icons are empty

### ISSUE THREAD

**Issue by chrismcmahon** [SalesforceFoundation/HEDAP#392]
Seen in Firefox and Chrome

This is Firefox: 

![screen shot 2017-02-13 at 10 21 10 am](https://cloud.githubusercontent.com/assets/204643/22894530/84f5c87a-f1d6-11e6-9a48-316cc83f3dca.png)

This is Chrome: 

![screen shot 2017-02-13 at 10 23 25 am](https://cloud.githubusercontent.com/assets/204643/22894541/900148ac-f1d6-11e6-9fa2-3483b2b7bd27.png)

**Comment by davidjray** [comment]
Which version of HEDA is this? I thought #370 addressed this.

**Comment by chrismcmahon** [comment]
obsolete HEDA version
