### ISSUE TITLE
Locker Service Error/Warning on HIPAA details field

### ISSUE THREAD

**Issue by davidjray** [SalesforceFoundation/HEDAP#393]
In Spring 17 with Locker Service enabled the HIPAA Detail field is disabled.

Screenshot:
![screen shot 2017-02-13 at 3 39 54 pm](https://cloud.githubusercontent.com/assets/4258978/22908374/ea2de69c-f202-11e6-98e0-ba5458a90d4a.png)

The error message states "Rich-text editing is disabled because the LockerService critical update is activated. Your Salesforce admin can deactivate the LockerService critical update in Setup."

**Comment by davidjray** [comment]
**lurch: add

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000050EkDAAU" target="_blank">W-017733</a>

**Comment by davidjray** [comment]
Tested in gs0 Org and this is now fixed.

Screenshot:
<img width="549" alt="screen shot 2017-04-28 at 3 28 06 pm" src="https://cloud.githubusercontent.com/assets/4258978/25549544/522f9ef8-2c27-11e7-8f40-e4788a86a6cb.png">
