### ISSUE TITLE
Preferred Email and Preferred Phone pick lists should have the ability to be localized

### ISSUE THREAD

**Issue by davidjray** [SalesforceFoundation/HEDAP#400]
The processing of Preferred email and Preferred Phone is hard coded in [CON_Preferred_TDTM](https://github.com/SalesforceFoundation/HEDAP/blob/master/src/classes/CON_Preferred_TDTM.cls) this prevents the default picklist values from being changed or translated.

**Comment by davidjray** [comment]
**lurch: attach W-018081

**Comment by davidjray** [comment]
**lurch: attach W-018081

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000005QCkhAAG" target="_blank">W-018081</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.42 (Beta 2)

**Comment by cpolcyn** [comment]
Included in production release rel/1.42
