### ISSUE TITLE
Investigation: Allow HEDA Relationship Reciprocal Settings to use hed__Gender__c

### ISSUE THREAD

**Issue by jacebryan** [SalesforceFoundation/HEDAP#404]
Power of US Idea owner: [Tom Neuburger](https://powerofus.force.com/_ui/core/userprofile/UserProfilePage?u=00580000006S8suAAC&tab=sfdc.ProfilePlatformOverview)
[Power of US Idea](https://powerofus.force.com/hub-ideas/1190)

Idea: Allow HEDA Relationship Reciprocal Settings to use hed__Gender__c

**Investigation is needed**
User is stating that even when a Gender is known that HEDA's Reciprocal Relationship Settings are overriding the Type value with the gender neutral value. Example provided by user: _This is particularly problematic when HEDA chooses "Siblings's Child" instead of Niece/ Nephew, or "Parent's Sibling" instead of Aunt/Uncle._ 

**Note:**
The steps below were captured by Jace in order to identify cause as well as to validate Idea request. There were a few things I came across that need to be investigated further to ensure accuracy in attempting to recreate issue identified by Tom vs. expected outcome of HEDA Reciprocal Settings.

**Create Relationship: Jane Doe (Aunt) to John Doe**

- Jane Doe does not have a salutation assigned on the Contact record
- Jane Doe is gender neutral on the Contact record
- Create a relationship between Jane Doe and John Doe (from John's Contact record) identifying Jane as the Aunt to John Doe
- From Jane Doe's Contact record the Related Contact for John Doe shows a Type value of “Sibling’s Child”
- From John Doe's Contact record the Related Contact for Jane Does shows a Type value of "Aunt"

 
**Create Relationship: Jimmy Doe (Uncle) to John Doe**

- Jimmy Doe does not have a salutation assigned on the Contact record
- Jimmy Doe is gender neutral on the Contact record
- Create a relationship between Jimmy Doe and John Doe (from John's Contact record) identifying Jimmy as the Uncle to John Doe
- From Jimmy Doe's Contact record the Related Contact for John Doe shows a Type value of "Sibling's Child"
- From John Doe's Contact record the Related Contact for Jimmy Doe shows a Type value of "Uncle"

 
**Assign a Gender value after Relationship has been created between 2 non-gender Contacts (INVESTIGATE)**

- Update the gender to “Female” for Jane Doe and refresh John Doe’s Contact record and the Type value of “Aunt” has been replaced with “Sibling’s Child”
- Update the gender to “Male” for Jimmy Doe and refresh John Doe's Contact record and the Type value of “Uncle” has been replaced with “Sibling’s Child”

 
**Create Relationship: Jenny Doe (Aunt) to John Doe (INVESTIGATE)**

- Jenny Doe was created with a salutation value of “Prof"
- Jenny Doe was assigned the value of “Female” for gender
- Create a relationship between Jenny Doe and John Doe (from John's Contact record) identifying Jenny as the Aunt to John Doe
- From John Doe's Contact record the Related Contact for Jenny Doe shows a Type value of "Aunt"
- Notice that because Gender was set before the relationship was established the Type value of "Aunt" stayed and did not update to "Sibling's Child" like it did for Jane Doe and Jimmy Doe.
- From Jenny Doe's Contact record the Related List for John Doe shows a Type value of “Sibling’s Child”

 
**Assign Gender value to John Doe (INVESTIGATE)**

When I set the Gender value of "Male" for John Doe's Contact record then the following occurs...

- John Doe's Type value changed from "Sibling's Child" to "Nephew" on both Jenny's and John's Contact Records.
- No change in Type value for the John Doe's relationships with Jane Doe and Jimmy Doe. Type values still show "Sibling's Child"

**Comment by davidjray** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000005fH6oAAE" target="_blank">W-018184</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.36 (Beta 3)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.36
