### ISSUE TITLE
HEDA error received as part of 1.30 release

### ISSUE THREAD

**Issue by jacebryan** [SalesforceFoundation/HEDAP#406]
This error is sent via email when a custom Preferred Email picklist value does not match the custom email field's "label". Note: the error does not prevent the record from being created.

For example:

- Custom email field Label: Custom Email Field
- Custom email field Label: FAFSA Email
- Preferred Email picklist value: No match

I do not receive an error email when I use the Preferred Email picklist value of "Custom Email Field" or "FAFSA"

Per @wongmike I am opening this up as a bug. @davidjray - this bug may be associated to the following 1.30 release change but I need you to confirm: **_Enhanced how the Preferred Email field controls email addresses for Contacts. Admins can now add custom email fields and add those fields as options in the Preferred Email field picklist._**

**Comment by davidjray** [comment]
**lurch: track W-018252

**Comment by davidjray** [comment]
**lurch: attach W-018252

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000005fHCcAAM" target="_blank">W-018252</a>

**Comment by kyleschmid** [comment]
FYI, an error here occurs in three scenarios:

1. One or more custom email fields exist on the Contact object and a Contact record has a non-null value for one of these fields and a null value in the Preferred_Email__c picklist

2. One or more custom email fields exist on the Contact object and a Contact record has a null value for all of these fields and a non-null value in the Preferred_Email__c picklist

3. A custom email field does not exist on the Contact object and a Contact record has a non-null value in the Preferred_Email__c picklist

Number 1 is thrown here: https://github.com/SalesforceFoundation/HEDAP/blob/master/src/classes/CON_Email.cls#L64-L68.

Number 2 and 3 are thrown here: https://github.com/SalesforceFoundation/HEDAP/blob/master/src/classes/CON_Email.cls#L82-L85

I'd say the method should ignore these records in this case. Or maybe an option on the HEDA settings page to control some of this.

**Comment by davidjray** [comment]
@kyleschmid thank you for your input!

The plan is to make the enforcements you pointed out configurable.

I do want to clarify that the bug reported here is not due to the designed "Preferred Email" enforcement. The error received is "Argument cannot be null.", which occurs when and Admin adds an option to the "Preferred Email" pick-list but doesn't have a matching custom email.

The "Argument cannot be null" error happens due to this line: 
https://github.com/SalesforceFoundation/HEDAP/blob/master/src/classes/CON_Email.cls#L70

I opened Issue #407 to help track the changes we are making.

**Comment by kyleschmid** [comment]
Yeah I see that the error is designed to be thrown. It just poses a problem for orgs that haven't adopted the HEDA Preferred Email field but still have a custom email field on the Contact object that's being used. Makes total sense to make it configurable. You may even want to disable it by default. A lot of users won't know to go to the settings screen to turn it off.

**Comment by davidjray** [comment]
That is great feedback @kyleschmid. The plan is to disable the validation by default for Orgs already using HEDA. For new installations of HEDA the validation with be activated by default.

**Comment by mrbelvedere** [comment]
Included in beta release 1.31 (Beta 3)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.31
