### ISSUE TITLE
Make Preferred Email enhancements introduced in 1.30 optional

### ISSUE THREAD

**Issue by davidjray** [SalesforceFoundation/HEDAP#407]
Due to the feedback received from the community we will make the Preferred Email enforcements optional.

**Comment by davidjray** [comment]
**lurch: attach W-018277

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000005kjj3AAA" target="_blank">W-018277</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.31 (Beta 3)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.31
