### ISSUE TITLE
Relabeled HEDA email fields and HEDA 1.33

### ISSUE THREAD

**Issue by vseafordACF** [SalesforceFoundation/HEDAP#412]
We've relabeled HEDA email fields (hed__AlternateEmail__c and hed__UniversityEmail__c) using the Translation Workbench Override.  With v1.33 in Sandbox, now when I try to save a contact record and the Preferred Email is selected and the Email is entered into the heda email field, the following message is displayed.  

"Error:We can't find the email specified in Preferred Email. Make sure that you're entering the field label of an existing custom email field."

The issue goes away when I remove the field override labels for the heda email fields and use the default field labels.

This is not an issue with v1.29.

**Comment by davidjray** [comment]
@vseafordACF What are the Overrides you added, and what value are you selecting in Preferred Email? 

Recent enhancements allow custom email fields labels to be added to the Preferred Email picklist. This allows custom email field values to be copied to the standard email field by selecting the custom email field in Preferred Email. The matching is done via the field label. In your case, since the label of the field was overridden via the translation workbench, you can add the new override value to the preferred email picklist and it should work as expected.

**Comment by vseafordACF** [comment]
Hi- thanks for the information.  I just tested, and I'm still seeing the Error message even when the Picklist label and Email label match.  See screenshot below.  Am I doing something wrong?


[cid:aa4d0c3a-e92f-48de-915f-5935559321b3]


Valenda Seaford

Principal Consultant
ACF Solutions<http://www.acfsolutions.com/>, An Attain Company
m: (804) 608-6351

________________________________

**Comment by davidjray** [comment]
@vseafordACF it looks like the screen shots didn't come through in the email reply to this thread on GitHub. Do you mind posting them here in GitHub? Thank you!

**Comment by vseafordACF** [comment]
Yes- no problem. 
![pastedimage](https://cloud.githubusercontent.com/assets/27836070/25291719/3bc4e078-26a1-11e7-9ef4-d464918a9949.png)

**Comment by davidjray** [comment]
@vseafordACF Did you add a new picklist value or edit an existing? Can you post a screenshot of the picklist value edit screen?

**Comment by davidjray** [comment]
@vseafordACF Also, can you please double check the version. Version 1.33 has been pushed to sandboxes but not production instances yet. The push to production instances is scheduled for May 2nd.

**Comment by vseafordACF** [comment]
This is in a sandbox with v1.33. We edited the label for existing picklist value.  Screenshot below.

![image](https://cloud.githubusercontent.com/assets/27836070/25292800/c70d67aa-26a5-11e7-9596-67d42bb8416f.png)

**Comment by davidjray** [comment]
Go ahead and also update the API Name value to match the display values. Let me know how that goes.

**Comment by vseafordACF** [comment]
Okay that works.  I had to set as the following-
![image](https://cloud.githubusercontent.com/assets/27836070/25297777/0b7a9e86-26be-11e7-8c30-0bd725aac1ed.png)

**Comment by wongmike** [comment]
@vseafordACF Thanks much for bringing this up. We will update our docs to reflect the change in behavior when using the Translation Workbench. For future issues, please help us by posting questions like this to the [Power of Us Hub - HEDA Chatter group](https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000D6uj) or by opening a support ticket. 

As much as possible, we'd like to keep Github populated with issues that can be worked by our Dev team.

Thanks much!

-mike

Mike Wong
Product Manager - Higher Education
Salesforce.org

**Comment by wongmike** [comment]
@lianeyee to update docs to reflect the fact that you need to update both the picklist label and the API Value for the custom email changes to be reflected when using Translation Workbench.
