### ISSUE TITLE
HEDA error when approving new accounts

### ISSUE THREAD

**Issue by jdaze10** [SalesforceFoundation/HEDAP#419]
Hi, we have an approval process setup on accounts.  We create them in one temporary record type and convert them to the official record type when approved.  This worked until the May HEDA update.  Now we are getting the following error when trying to approve accounts.  Any thoughts?

Thanks!!

Error thrown when approving the creation of a new account.

Validation Errors While Saving Record(s)
There were custom validation error(s) encountered while saving the affected record(s). The first validation error encountered was "Apex trigger hed.TDTM_Account caused an unexpected exception, contact your administrator: hed.TDTM_Account: execution of AfterUpdate caused by: System.NullPointerException: Attempt to de-reference a null object: Class.hed.AFFL_MultiRecordTypeMapper.getKeyAfflFieldByAccRecordType: line 139, column 1".

**Comment by jacebryan** [comment]
HI @jdaze10 - Please move this question to the HEDA User Group in the Power of US Hub so we can address your question in the community. Here is a little background on how Issues works in Github so you understand why I am asking you to move this discussion to the PUB: 

Issues in Github should only be created if you've encountered a bug with a Release. Errors, like what you've encountered, should always be posted in the PUB and reported to salesforce customer support for resolution. However, if the error you encountered is understood by you and you know how to fix it you could submit a Pull Request to address the fix in code.

You can find me in the PUB so feel free to reach out to me there if you need additional information on the use of Github. I'm always willing to talk about it :)

Thank you!

**Comment by jdaze10** [comment]
Thanks I did create a case to resolve as well.

**Comment by jacebryan** [comment]
Thank you @jdaze10! I am going to look for your PUB post in just a few minutes. I'll be closing this Issue out now.
