### ISSUE TITLE
NullPointerException when trying to change Account record type

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#422]
When you try to change the record type of an account you get a NPE:

![screen shot 2017-05-12 at 3 25 23 pm](https://cloud.githubusercontent.com/assets/1894238/26015607/54b5b404-3727-11e7-908e-9425a1cc4cd3.png)

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000006JX9dAAG" target="_blank">W-018647</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.35 (Beta 2)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.35
