### ISSUE TITLE
TDTM not respecting "User Managed" field on trigger handlers

### ISSUE THREAD

**Issue by davidjray** [SalesforceFoundation/HEDAP#424]
User Jim Hubert in the Power of Us Hub alerted us to this issue here: https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000DA0Q&fId=0D58000003LKN3Z&fromEmail=1

**Comment by davidjray** [comment]
**lurch: attach W-018664

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000006PFW4AAO" target="_blank">W-018664</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.35 (Beta 3)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.35
