### ISSUE TITLE
Auto set Preferred Email when only one custom email field is present

### ISSUE THREAD

**Issue by davidjray** [SalesforceFoundation/HEDAP#428]
As part of the Preferred Email field enforcement, we should auto set Preferred Email and the Standard Email field when a single custom email field has a value.

This allows a better user experience and better compatibility when converting leads.

**Comment by davidjray** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000006PLJMAA4" target="_blank">W-018688</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.35 (Beta 5)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.35
