### ISSUE TITLE
 List index out of bounds error appears when updating the Primary Contact on a Course Offering

### ISSUE THREAD

**Issue by jacebryan** [SalesforceFoundation/HEDAP#443]
Issue identified via [CSG Case](https://org62.lightning.force.com/one/one.app#/sObject/5000M00000haoMkQAI/view)

Based on conversation with @ceiroa yesterday:

The stack trace in the attached file doesn't really have any useful info. I think that's the internal stack trace.
 
Error loading into target [hed__Course_Offering__c] : Error received from salesforce.com. Fields []. Status code [CANNOT_MODIFY_MANAGED_OBJECT]. Message [hed.TDTM_CourseOffering: execution of AfterUpdatecaused by: System.ListException: List index out of bounds: 1(hed)].
 
Somewhere in TDTM_CourseOffering we are trying to read from an empty list.
 
There is only one class that runs on the Course_Offering__c object
 
(TDTM_CourseOffering is the trigger)
 
The class is COFF_Affiliation_TDTM
 
So somewhere in COFF_Affiliation_TDTM we are trying to read the first record from a list that doesn't have records
 
They could potentially fix it by changing the data they are loading, but very hard to figure out how to change it
 
It seems like a bug on our side, where we are not checking if the list is empty before trying to read from it

**Comment by jacebryan** [comment]
@ceiroa - can you please lurch this for me?

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000006uQONAA2" target="_blank">W-019067</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.38 (Beta 4)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.38
