### ISSUE TITLE
ADDR_Contact_TDTM too many chunks error

### ISSUE THREAD

**Issue by kyleschmid** [SalesforceFoundation/HEDAP#447]
The propagateAddrInfo and createAddrsFromContacts methods of ADDR_Contact_TDTM throw a "System.TypeException: Cannot have more than 10 chunks in a single operation. Please rearrange the data to reduce chunking." in some cases. This is because contacts/accounts are being added to the objectsToUpdate list in an unsorted manner. I will submit a pull request.

**Comment by jacebryan** [comment]
WI was created: https://foundation--agf.na6.visual.force.com/apex/adm_bugdetail?id=a2x800000076CaDAAU&sfdc.override=1

**Comment by davidjray** [comment]
**lurch: attach W-019199

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000076CaDAAU" target="_blank">W-019199</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.38 (Beta 2)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.38
