### ISSUE TITLE
Admin Account is not created when a Contact is created

### ISSUE THREAD

**Issue by davidjray** [SalesforceFoundation/HEDAP#455]
Introduced from recent TDTM updates. 

TDTM_Config.getClassesToCallForObject() is sorting the tokens via a FOR loop with an integer key. Now that we are using DECIMALS for the load order field we cannot access the tokens via the for loop integer key.

**Comment by davidjray** [comment]
**lurch: attach W-019290

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007CB9BAAW" target="_blank">W-019290</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.37 (Beta 8)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.37
