### ISSUE TITLE
Deleted Relationship record prevents deleting Contact

### ISSUE THREAD

**Issue by chrismcmahon** [SalesforceFoundation/HEDAP#458]
Create two Contacts 'First' and 'Second'.

Create a Relationship record for the two Contacts. 

Attempt to delete a Contact. Get error "Your attempt to delete First could not be completed because it is associated with the following relationships..." See screen shot. 
![screen shot 2017-07-06 at 2 38 14 pm](https://user-images.githubusercontent.com/204643/27934070-e91d7d50-6258-11e7-89e3-2b1af058ee0c.png)

Delete the Relationship record. 

Attempt to delete the Contact again. Get error 

There were custom validation error(s) encountered while saving the affected record(s). The first validation error encountered was "Apex trigger hed.TDTM_Contact caused an unexpected exception, contact your administrator: hed.TDTM_Contact: execution of AfterDelete caused by: System.ListException: Missing id at index: 0: (hed)". 
![screen shot 2017-07-06 at 2 39 51 pm](https://user-images.githubusercontent.com/204643/27934095-0b4b98e4-6259-11e7-90c7-6b89bafb7f0e.png)

**Comment by chrismcmahon** [comment]
Note that similar to a Relationship, an Affiliation on a Contact will prevent the deletion of the Contact, but after deleting the Affiliation record, the Contact in question may be deleted properly.

**Comment by davidjray** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007CGprAAG" target="_blank">W-019339</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.39 (Beta 1)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.39
