### ISSUE TITLE
Allow default HEDA Email field labels to be overridden

### ISSUE THREAD

**Issue by davidjray** [SalesforceFoundation/HEDAP#459]
Background info can be found in this [thread in the hub](https://powerofus.force.com/_ui/core/userprofile/UserProfilePage?u=0058000000ABNmU&tab=sfdc.ProfilePlatformFeed&fId=0D58000003VU9Tm&fromEmail=1).

We need to make an easy way for admins to overwrite the default values for the preferred email picklist on contacts. The behavior should be consistent with the current version of the platform.

The CON_Preferred_TDTM class is still on API version 35 and it should be at least 39 to support the new Name-Value pair feature for picklists. We should investigate the consequences of updating this specific class API version.

Currently, if you overwrite the label of a preferred email picklist value (not the API value) and overwrite a HEDA email field label you'll get the error "We can't find the email specified in Preferred Email. Make sure that you're entering the field label of an existing custom email field." This may be due, partially, to the API version of the class.

**Expected behavior:** An admin should be able to overwrite the Label of a picklist value for Preferred Email and overwrite the label of a default HEDA field and be able to save the contact record correctly.

**Comment by davidjray** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007I7A3AAK" target="_blank">W-019381</a>

**Comment by davidjray** [comment]
This is already supported by editing the label of a picklist but leaving the API Value. For example, if an Admin wanted to append "Email" to the picklist options the configuration should look like the screenshot below.

![screen shot 2017-07-10 at 5 41 07 pm](https://user-images.githubusercontent.com/4258978/28077893-eb5414f4-6617-11e7-95e5-04a6b1d1fcac.png)
