### ISSUE TITLE
Possible duplicate trigger handlers created upon package upgrade after 1.37

### ISSUE THREAD

**Issue by davidjray** [SalesforceFoundation/HEDAP#461]
In certain cases, trigger handlers could be deleted or duplicated when HEDA is upgraded.

The recent push of HEDA 1.37 may have deleted users custom trigger handlers when "User Managed" wasn't checked. 

We should update all Trigger handlers in the HEDA scope to use the "Owned by namespace" field before processing so HEDA Handlers are targeted specifically in future updates, and Users custom trigger handlers are not touched.

Also, future upgrades to HEDA 1.38 and above could create duplicate Trigger Handlers when Admins set the  "user Managed" field to true.

**Comment by davidjray** [comment]
**lurch: attach W-019441

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007ICRWAA4" target="_blank">W-019441</a>

**Comment by davidjray** [comment]
After looking into this it was determined that the deletion of trigger handlers with 1.37 was part of the normal operation of the package. With additional enhancements released with 1.37 developers can utilize the "Owned by Namespace field added to the HEDA Trigger Handler object. 

There are now two ways to prevent deletion of trigger handlers. You can use the User_Managed__c field or the Owned_by_Namespace__c field. The usage of Owned_by_Namespace__c is the preferred method.

**Comment by mrbelvedere** [comment]
Included in beta release 1.38 (Beta 5)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.38
