### ISSUE TITLE
Edit Account Model

### ISSUE THREAD

**Issue by Btibert3** [SalesforceFoundation/HEDAP#466]
I wanted to play around with the current App in a clean Sandbox, but after a clean setup of a developer org and using the button-click install, I can't seem to review/edit my account setup.  See picture below, as there is no option to select.

![image](https://user-images.githubusercontent.com/203343/28329317-6cfa8318-6bb7-11e7-9282-fd2df4a134e9.png)

Likely user error on my end, but after a clean dev org setup and install of HEDA, not sure what it would be.

Thanks for your help on this!

Brock

**Comment by jacebryan** [comment]
@Btibert3 - I believe this is because you don't have the Account record types assigned to your profile. Check that next. 

As a side note - Issues like this should be brought up in the Power of US Hub HEDA group and not in Github. Here is a PUB post that explains how Github should be used: https://powerofus.force.com/0D58000003LK7N3

Thank you! :)

**Comment by Btibert3** [comment]
Thanks for the reply. Is the content gated?  How can I join?

See screenshot below.  I worked in higher ed for 11+ years within Enrollment Management at an accredited institution prior to my new role (still focused on assisting higher ed clients), so I am not sure where to best target my questions as I explore use-cases and solutions in a market that I am very passionate about.

Thanks in advance.

![image](https://user-images.githubusercontent.com/203343/28347444-150ab6ac-6c05-11e7-9a79-a138443ac816.png)

**Comment by jacebryan** [comment]
@Btibert3 - Please take a look at this external knowledge article for assistance with this issue: https://help.salesforce.com/articleView?id=Power-of-Us-Hub&language=en_US&type=1

Let me know if you are able to login after reviewing this information.

**Comment by Btibert3** [comment]
Thanks for this, but based on those guidelines, I am not eligible to participate/log in.  I would love to participate in the discussions and follow along with the development, but it doesn't appear that I can at this time.  

Thanks again for your help, much appreciated.
