### ISSUE TITLE
ACCT_IndividualAccounts does not change Account owner when contact owner changes

### ISSUE THREAD

**Issue by Kamilsz** [SalesforceFoundation/HEDAP#468]
Hi,
We are trying to implement TDTM in our org and have found following problem.

Line:
`if (c.OwnerId != oldContacts[i].OwnerId) {
						mapContactIdContactOwnerChange.put(c.Id, c);
					}`
does not pick up the change.
c.OwnerId and OldContacts[i].OwnerId are the same at the time when trigger fires, they both have the value of the old OwnerId.

I tried following test method and it fails at the last assertion:
`@isTest
	public static void changeOwner () {

		Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User'];
		User u1 = new User (Alias = 'standt1', Email = 'standarduser1@testorg.com',
				EmailEncodingKey = 'UTF-8', LastName = 'Testing', LanguageLocaleKey = 'en_US',
				LocaleSidKey = 'en_US', ProfileId = p.Id,
				TimeZoneSidKey = 'America/Los_Angeles', UserName = 'test1@ahpra.gov.au');
		insert u1;

		Contact con = new Contact (
				FirstName = 'Test',
				LastName = 'Contact_forTests',
				Email = 'junk@test.net',
				OwnerId = UserInfo.getUserId()
		);
		insert con;

		con = [select AccountId, OwnerId from Contact where id = :con.Id];
		Account newAcc = [select id, OwnerId, Primary_Contact__c from Account where id = :con.AccountId limit 1];

		//change owner of the contact
		con.OwnerId = u1.id;
		Test.startTest();
		update con;
		Test.stopTest();

		con = [select AccountId, OwnerId from Contact where id = :con.Id];
		System.assert(u1.Id == con.OwnerId, 'Current user is not the owner of the contact');

		newAcc = [select id, OwnerId from Account where id = :con.AccountId limit 1];

		System.assertEquals(con.OwnerId, newAcc.OwnerId, 'Account\'s owner id should be the same as contact\'s');

	}
`

Regards,
Kamil

**Comment by jacebryan** [comment]
@Kamilsz  - My recommendation is that you ensure the account has a record type. Here is a related Issue: https://github.com/SalesforceFoundation/HEDAP/issues/221

As a side note - Issues like this should be brought up in the Power of US Hub HEDA group and not in Github. Here is a PUB post that explains how Github should be used: https://powerofus.force.com/0D58000003LK7N3

Thank you! :)
