### ISSUE TITLE
404 error loading the HEDA "Courses" ApexDoc page

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#470]
Go to the HEDA ApexDocumentation page: http://developer.salesforce.org/HEDAP/ApexDocumentation/index.html 

Click the Courses link. The target page results in a file not found error: http://developer.salesforce.org/HEDAP/ApexDocumentation/Courses.html 

An attendee at last week's Higher Ed Sprint reported this error.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000065rE8AAI" target="_blank">W-019883</a>

**Comment by cpolcyn** [comment]
Included in beta release 1.41 (Beta 4)

**Comment by cpolcyn** [comment]
Included in production release rel/1.41
