### ISSUE TITLE
ApexDocs site menu not opening correctly in some sections

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#471]
Go to the HEDA ApexDocumentation page: http://developer.salesforce.org/HEDAP/ApexDocumentation/index.html.

Click sections in the left menu. They don't stay open, so you cannot click the actual classes.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000065rErAAI" target="_blank">W-019884</a>

**Comment by robertbwatson** [comment]
The work item for this issue was closed last year, so I am closing this issue. Please let me know if that's not the correct process.
