### ISSUE TITLE
TDTM_Global_API getTdtmConfig does not return customized TDTM configuration in unit tests

### ISSUE THREAD

**Issue by kevinswiggum** [SalesforceFoundation/HEDAP#479]
If a developer is running custom unit tests that interact with HEDA objects, the TDTM configuration is able to return the default trigger handler configuration without requiring any Trigger_Handler__c setup records. The configuration is built on-the-fly.

However, if a developer wants to customize the Trigger Handler setup, they can do so via TDTM_Global_API.setConfig. Within the same transaction, though, the getTdtmConfig will still return the HEDA default configuration. This can have strange results: records inserted during testSetup will  use the default HEDA TDTM configuration but the actual test method will use the custom TDTM config (since the test method starts another transaction). 

getTdtmConfig stores and returns a cached version of the configuration and there's not a simple way to clear it and pull the customized version within the same transaction.

**Comment by kevinswiggum** [comment]
**lurch:add

**Comment by kevinswiggum** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000005uYo7AAE" target="_blank">W-020346</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000005uYpLAAU" target="_blank">W-020347</a>

**Comment by ceiroa** [comment]
This sounds really familiar. Didn't we already fix this, @davidjray / @xinnanlisf? Or did we just talk about it but never opened a work item?

**Comment by ceiroa** [comment]
@kevinswiggum Did this come from the Hub? I'm trying to remember the history of this, and the post would help, if there is one. Thanks!

**Comment by kevinswiggum** [comment]
@ceiroa Yes it came from a post by Brian Petersen: https://powerofus.force.com/_ui/core/userprofile/UserProfilePage?u=0058000000ABNmU&tab=sfdc.ProfilePlatformFeed

TDTMConfig list was getting cached as our defaults and there wasn't a great way to clear the cache during unit testing to force a re-pull from Trigger_Handler__c. I gave him a workaround but it's a bit clunky

**Comment by mrbelvedere** [comment]
Included in beta release 1.45 (Beta 3)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.45
