### ISSUE TITLE
Contact side menu for apexDoc page won't open

### ISSUE THREAD

**Issue by xinnanlisf** [SalesforceFoundation/HEDAP#482]
When clicking on contacts, it redirects the users to account.htm

**Comment by xinnanlisf** [comment]
**lurch: attach W-020361

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000005ucyEAAQ" target="_blank">W-020361</a>

**Comment by cpolcyn** [comment]
Included in beta release 1.41 (Beta 4)

**Comment by cpolcyn** [comment]
Included in production release rel/1.41
