### ISSUE TITLE
Avoid attempting email sends in unit tests

### ISSUE THREAD

**Issue by weizsforg** [SalesforceFoundation/HEDAP#490]

**Comment by weizsforg** [comment]
**lurch: attach W-008470

**Comment by xinnanlisf** [comment]
**lurch: attach W-008470

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000001gAoAAI" target="_blank">W-008470</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.43 (Beta 1)

**Comment by cpolcyn** [comment]
Included in production release rel/1.43
