### ISSUE TITLE
Implement Spanish Translation

### ISSUE THREAD

**Issue by xinnanlisf** [SalesforceFoundation/HEDAP#492]
As a Spanish speaking HEDA user/customer/partner
I would like the new Spanish translations to be implemented
so that we can use HEDA specific items in Spanish

**Comment by xinnanlisf** [comment]
**lurch: attach W-020438

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000008FA4DAAW" target="_blank">W-020438</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.43 (Beta 2)

**Comment by cpolcyn** [comment]
Included in production release rel/1.43
