### ISSUE TITLE
MANAGER GIT: Winter 18 Search Result Field Issue

### ISSUE THREAD

**Issue by jacebryan** [SalesforceFoundation/HEDAP#501]
Found by: Kevin Swiggum
Addressing CSG case: 17370350

**Customer Issue Encountered:**

When looking at the search results in a Winter 18 HEDA org you will see that for the column “Address” the word “USA” is partially cut off. 

**Technical Review of Issue:**

Classifying this as a Winter 18 issue....and partially intended. Right now, if there are 3 lines in a search result field, the length of the 3rd line is cut off to match the max length of the first two lines. So the "USA" is getting cut off because the street and city/state/zip lines are really short.
 
They're doing this as a visual indicator to show that more data exists in a field than what they're seeing in the search results. The strange part is that the 3rd line cuts off based on the length of the top two lines rather than looking at the available width of the column.

**Steps to Reproduce:**

1. Log into a Winter 18 HEDA org
2. Create a Contact and include the following information for Address:
   2a. Mailing Street = 1234
   2b. Mailing City = test
   2c. Mailing State/Province = test
   2d. Mailing Zip/Postal Code = test
   2e. Mailing Country = United States
3. Edit the Address Object Search Layout for "Search Results" and include the field "Mailing Address"
4. Copy and Paste the Address-ID into the Search bar and hit the Enter key
5. From the Search Results page click on the "Show More" link to expand additional Search options
6. Select Addresses
7. You will see where the issue is occurring in the Search Results view

**Current Workaround:**

None

**Comment by jacebryan** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000001SCBbAAO" target="_blank">W-020923</a>

**Comment by jacebryan** [comment]
![screenshot](https://user-images.githubusercontent.com/25934611/31730817-bed7411a-b3f8-11e7-9dc7-aa64484deaa1.jpg)

**Comment by kbromer** [comment]
Do we have any control over this behavior? I'm not sure its useful for us to log a bug here, when it should probably be sitting with core, no?

**Comment by jacebryan** [comment]
@kbromer - You are correct. We don't have control over this behavior since it seems to be a core issue. However, because this issue was reported via Case by a customer, I felt it necessary to create the Issue here so the HEDA community understands that this is not a HEDA issue but a Core issue. I've discussed this Issue with the HEDA PM and he will be escalating it to Core so they are aware of the impact. Once Core resolves the Issue we can close this Issue out along with the WI on our end.

**Comment by jacebryan** [comment]
@kbromer - Based on our discussion I've created a new label called: core bug.

**Comment by jacebryan** [comment]
Update!

The "fade" is an updated UI improvement in Winter '18. This is NOT a core bug but is working as designed.

Closing this WI now.
