### ISSUE TITLE
Error Message: The post install script failed.

### ISSUE THREAD

**Issue by malleladeepak** [SalesforceFoundation/HEDAP#506]
Please help me to fix the below issue ASAP.

Your request to install package "HEDA HEDA 1.42" was unsuccessful. None of the data or setup information in your salesforce.com organization was affected.
If your install continues to fail, contact Salesforce CRM Support through your normal channels and provide the following information.
Organization: Boston University IS&T (00Dc0000003w9fp)
User: Brad Peloquin (005460000013n2J)
Package: HEDA (04t360000011yy2)

Problem:
1. Unexpected Error
The package installation failed. Please provide the following information to the publisher:
Organization Name: Boston University IS&T Organization ID: 00Dc0000003w9fp

Package: HEDA
Version: 1.42
Error Message: The post install script failed.

**Comment by jacebryan** [comment]
Hi @malleladeepak - Errors, like what you've encountered, should always be posted in the PUB and reported to Salesforce Support for resolution. They should not be submitted as an Issue in Github. 

You can find me in the PUB so feel free to reach out to me there if you need additional information on the use of Github. I'm always willing to talk about it :)

As a side note - Here is a PUB post that explains how Github should be used: https://powerofus.force.com/0D58000003LK7N3

I'll be closing this Issue out now.

Thank you! :)
