### ISSUE TITLE
REL_Relationships_TDTM gives Entity is Deleted error

### ISSUE THREAD

**Issue by kyleschmid** [SalesforceFoundation/HEDAP#510]
When trying to delete all relationships for a Contact in a single operation, the REL_Relationships_TDTM trigger deletes the reciprocal relationships in the middle of the delete. This causes an Entity is Deleted error when the delete attempts to complete.

I've updated the trigger to keep track of what relationships have been deleted and submitted a pull request.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000008jBZ2AAM" target="_blank">W-021097</a>

**Comment by weizsforg** [comment]
Hi @kyleschmid , can you please provide more detail about how to reproduce the error?
It will be good If you can provide a simple code example about how do you query all relationships of a Contact and delete them.

**Comment by kyleschmid** [comment]
Hi @weizsforg, this code in execute anonymous will reproduce the error:
`Contact c1 = new Contact(LastName = 'test1');
Contact c2 = new Contact(LastName = 'test2');
insert new List<Contact>{c1, c2};

insert new hed__Relationship__c(hed__Contact__c = c1.Id, hed__RelatedContact__c = c2.Id);
delete [SELECT Id FROM hed__Relationship__c WHERE hed__Contact__c = :c1.Id OR hed__Contact__c = :c2.Id];`

**Comment by mrbelvedere** [comment]
Included in beta release 1.47 (Beta 2)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.47
