### ISSUE TITLE
Correct misleading comment in ACCT_IndividualAccounts_TDTM.cls

### ISSUE THREAD

**Issue by xinnanlisf** [SalesforceFoundation/HEDAP#512]
There is a comment in ACCT_IndividualAccounts_TDTM.cls which is not accurate:

// if the last name of contact has changed and it is using admin account model 
// change the related admin account last name

**Comment by xinnanlisf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000008jEjiAAE" target="_blank">W-021112</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.48 (Beta 3)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.48
