### ISSUE TITLE
Update @parameter annotations. It should be @param.

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#515]
ApexDocs displays "eter" instead of the parameter name. Most likely because the annotation is incorrect. 

Left is HEDA, right is NPSP:
![screen shot 2017-11-27 at 3 43 12 pm](https://user-images.githubusercontent.com/1894238/33292525-2d8ae2f0-d38f-11e7-84bb-eac11ac449e7.png)

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000008v6URAAY" target="_blank">W-021356</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.48 (Beta 3)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.48

**Comment by robertbwatson** [comment]
The work item for this was closed and it looks like this was released in Feb 2018 - so I think this issue can be closed. I am closing it, but if there's a different process that should be followed please let me know.
