### ISSUE TITLE
Deploying the /src folder to a dev sandbox

### ISSUE THREAD

**Issue by jayonsoftware** [SalesforceFoundation/HEDAP#517]
I am trying to deploy the /src folder to a brand new sandbox and keep getting these errors. 

![image](https://user-images.githubusercontent.com/1304943/34077846-b8327afc-e2db-11e7-98ea-564b5dcc31fe.png)

Any thoughts on what I am dong wrong ?

Jay

**Comment by ceiroa** [comment]
Hi @jayonsoftware. We appreciate your interest in HEDA. However, in the future please post first at The Power of Us Hub (powerofus.force.com - it's free!) before opening a Github ticket.

We'd highly recommend installing the manage version of the package, which  you can obtain from mrbelvedere.salesforcefoundation.org/mpinstaller/hed. Among other things, that will guarantee automatic updates to the latest version. Also, the installer will take care of all requirements. One of the requirements is having at least one Account record type in the org. This is the requirement that is missing for you. If you are certain you want to install the unmanaged code, first create an Account record type in the org.

Thanks!
