### ISSUE TITLE
TDTM duplicate fields selected error

### ISSUE THREAD

**Issue by weizsforg** [SalesforceFoundation/HEDAP#518]
There is a "duplicate field selected error" that has been reported by 2 community members (see Reference below) that we know of. 

Reference:
Error reported by Kalman: https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000D6uj&fId=0D58000003dzCi3
Error reported by Richard: https://powerofus.force.com/_ui/core/userprofile/UserProfilePage?u=0058000000DCwx7&tab=sfdc.ProfilePlatformFeed&fId=0D58000003hFzwD

Jace is working to confirm if Richard's scenario is the same as Kalman's (i.e. Changed the Record Type Label of an Account & including modifications to Affiliation Mappings).

Although there is a workaround for Kalman's issue (see workaround steps below), we should do more investigations to confirm the cause. 

Workaround:
You can get around the duplicate field error by going to Setup > Installed Packages > HEDA > View Components > Affl Mappings > Manage > Edit Program Plan and remove the value for Primary Affl Field. Do your bulk upload and then put the value back in the Primary Affl Field.

**Comment by weizsforg** [comment]
**lurch: attach W-020813

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000008YdAPAA0" target="_blank">W-020813</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.47 (Beta 3)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.47
