### ISSUE TITLE
System populates the wrong Primary field when change Account record in batch mode

### ISSUE THREAD

**Issue by weizsforg** [SalesforceFoundation/HEDAP#524]
When we change the Account Record type from a record type didn't have a primary affiliation mapping (e.g. Admin) to a record type has a primary affiliation mapping (e.g. Academic Program), system will update the corresponding Primary Field on a Contact. It works when user try to update Account record type one by one. However, system will populate extra Primary Field on Contact if the user update multiple Account record type in batch mode. 

For example, 
1. Create two Contacts: A, B
2. Create two Accounts: Math, Football. Set both record type to Admin first
3. Create two Affiliations: A - Math, B-Football. Currently, the primary fields on A and B should be empty 
4. Update Accounts in one operation: Math - Academic Program, Football - sports organization
5. System should update Primary Academic Program of A and the Primary sports org of B. However, you will see both Primary Academic Program, Primary sports org of A becomes Math (similar thing happen to B). Which is not correct.

**Comment by mrbelvedere** [comment]
Included in beta release 1.47 (Beta 3)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.47
