### ISSUE TITLE
Filter Field / Filter Value Bug on Trigger Handler Object

### ISSUE THREAD

**Issue by sam-knox** [SalesforceFoundation/HEDAP#538]
When you set a Filter Field and Filter Value on a Trigger Handler record, the filtering works fine but an error is thrown if the target object's field data is changed.

**Steps to reproduce**
1. Update the Trigger Handler that manages the CON_DoNotContact_TDTM class with these two values: Filter Field = Citizenship__c
Filter Value = Aruba
2. Create a Contact and set the Citizenship field to Aruba and Save. 
3. Try to change the Citizenship field to any other value. Error is thrown.

Error message reads:
hed.TDTM_Contact: execution of BeforeUpdate caused by: System.ListException: List index out of bounds: 0 (hed)

I tried the same thing above with a different trigger handler and got the same error. Seems to be an issue with any of them.

**Comment by sam-knox** [comment]
**lurch: add

**Comment by weizsforg** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009Ue4JAAS" target="_blank">W-022514</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.51 (Beta 4)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.51
