### ISSUE TITLE
Filter Field on Trigger Handler doesn't work with Number/Currency fields

### ISSUE THREAD

**Issue by sam-knox** [SalesforceFoundation/HEDAP#539]
If you select a Number, Currency, or any field that uses numeric data type (i.e. percentage, rollup summary, formula) the TDTM filtering doesn't work. The class is still run.

**Steps to Reproduce**

1. Create custom field on Contact such as Household Income (Currency 18,0)
2. Set the Filter Field on a Contact-related Trigger Handler (such as CON_DoNotContact_TDTM) to Household_Income__c
3. Set the Filter Value to 50000
4. Create or update a Contact with 50000 in the Household Income field
5. Check Deceased and Save
6. Notice that the trigger runs even though there is a filter

I tested the above with a simple Number field and a Rollup Summary field that returns a number and got the same result.

**Comment by sam-knox** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009UgSaAAK" target="_blank">W-022534</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.51 (Beta 5)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.51
