### ISSUE TITLE
System use the wrong 'Work Email' for Prefer email when the org has HEDA and NPSP

### ISSUE THREAD

**Issue by weizsforg** [SalesforceFoundation/HEDAP#543]

**Comment by weizsforg** [comment]
**lurch: attach W-021969

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009FE57AAG" target="_blank">W-021969</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.51 (Beta 1)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.51
