### ISSUE TITLE
Populate Role for Affiliation in HEDA

### ISSUE THREAD

**Issue by jacebryan** [SalesforceFoundation/HEDAP#547]
**HEDA Idea:** [Populate Role for Affiliation in HEDA](https://powerofus.force.com/hub-ideas/1293)
**Created by:** [Kalman Sweetwine (University of Colorado System Enterprise Org)](https://powerofus.force.com/_ui/core/userprofile/UserProfilePage?u=00580000005Q6LhAAK&tab=sfdc.ProfilePlatformOverview
)
**Supporting use case:** [Matthew Blanski (Illinois Institute of Technology)](https://powerofus.force.com/_ui/core/userprofile/UserProfilePage?u=0058000000DGqt2&tab=sfdc.ProfilePlatformFeed)

**Idea:**

Use Case: In HEDA - I create a New Program Enrollment for a Student. The Program on the Program Enrollment is an Account with RecordType = Academic Program.

So when I create the Program Enrollment > HEDA trigger creates an Affiliation with Status=Current.
I also expect Role=Student in this case (since it is an academic program). However, this use case may have more options for Role (eg. faculty, TA, etc. etc.). Adding the ability to set Role via HEDA settings would be a big benefit to controlling workflow, etc.

Instead (our work around) is a trigger to populate the Affiliation.Role with Student for this specific use case.

**Analysis:**

What's missing on the auto-created Affiliation is values for Status and Role....our PREN trigger handler just leaves them blank. The Idea is asking for additional configuration to say if Program Enrollment record is created, in addition to auto creating the Affiliation, also populate Status and Role with values determined in HEDA Settings. Right now we don't have any settings that have to do with Program Enrollments...so this would be a new tab in HEDA Settings...or maybe a Program Enrollment tab beneath the Affiliations tab.

**Comment by jacebryan** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009gNsWAAU" target="_blank">W-022828</a>

**Comment by mrbelvedere** [comment]
Included in production release 1.68
