### ISSUE TITLE
Primary Contact: moving a primary contact from one household to another household makes that contact the primary account of the household it was moved too

### ISSUE THREAD

**Issue by annejackson** [SalesforceFoundation/HEDAP#562]
This should not happen.  

My default account model was Household and I had automatic household naming on.

Steps to duplicate:
1. Create a contact. It will automatically be the primary contact for this household. 
2. (not sure this step is necessary) Un-associate the contact as the primary contact (make it blank) for that household. Then re-associate the contact as the primary contact.
3. Go back to Contacts and create a brand new contact to be auto-assigned a new household account. This contact will be the primary contact for this household.
4. Move the contact created in step 1/2 to the household created in step 3 . 
Expected:
The moved contact should NOT be listed as the primary contact to the moved account/household from step 3. It should also still be listed as the primary contact for the old/blank/anonymous household.

Actual: 
The moved contact WAS listed as the primary contact to the moved account/household from step 3 (incorrect). It was listed as the primary contact for the old/blank/anonymous household. (correct)

**Comment by annejackson** [comment]
**lurch:add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009x9f1AAA" target="_blank">W-023188</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.51 (Beta 6)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.51
