### ISSUE TITLE
GDPR: Emailing error log should be disabled by default

### ISSUE THREAD

**Issue by lparrott** [SalesforceFoundation/HEDAP#567]
In order to comply with GDPR, the checkbox under HEDA settings for emailing the contents of the asynchronous jobs error log should be disabled by default.

We do not need to worry about existing orgs, and they can disable it themselves.

**Comment by lparrott** [comment]
**lurch: attach W-022882

**Comment by lparrott** [comment]
**lurch:attach W-022882

**Comment by ceiroa** [comment]
**lurch:attach W-022882

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009llaHAAQ" target="_blank">W-022882</a>

**Comment by lparrott** [comment]
@ceiroa Do I need permissions added to my account for lurch? I'm also unable to make a pull request...

**Comment by ceiroa** [comment]
@lparrott Yes. Talk with @cpolcyn for that!

**Comment by cpolcyn** [comment]
@lparrott 
Actually I don't have permissions to do that. You'll need to file a Case in WLMA so that EntSys can get you set up.

**Comment by lparrott** [comment]
**lurch: detach

**Comment by lparrott** [comment]
**lurch:attach W-022882

**Comment by LurchTheButler** [comment]
Detached <a href="https://foundation.my.salesforce.com/a2x80000009llaHAAQ" target="_blank">W-022882</a>

**Comment by lparrott** [comment]
**lurch:attach W-022882

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009llaHAAQ" target="_blank">W-022882</a>

**Comment by LurchTheButler** [comment]
Detached <a href="https://foundation.my.salesforce.com/a2x80000009llaHAAQ" target="_blank">W-022882</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.51 (Beta 2)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.51
