### ISSUE TITLE
Implemented internal TDTM enhancements of HEDA to support future development

### ISSUE THREAD

**Issue by weizsforg** [SalesforceFoundation/HEDAP#570]

**Comment by weizsforg** [comment]
**lurch: attach W-021136

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000008mwirAAA" target="_blank">W-021136</a>

**Comment by annejackson** [comment]
@weizsforg can you put some high-level Dependency injection and logic check info in this ticket (how does it work) and also what to test on the HEDA side? Thanks!
I've added some notes to W-021136 as well.

**Comment by mrbelvedere** [comment]
Included in beta release 1.53 (Beta 1)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.53
