### ISSUE TITLE
"Student" record type does not work on french version

### ISSUE THREAD

**Issue by brds81** [SalesforceFoundation/HEDAP#579]
Hi,
If we change the label of the record type "Student" to another label on the Translation workbench, it seems that the course connection is not saved.
The fact that we change only the label (not the unique name), it's strange that we can't translate.
Is it possible to log this ussue? Indeed, I have a french client and it will be great to change this label if needed.
Thanks a lot for your feedback

**Comment by jacebryan** [comment]
Hi @brds81 - Thanks for creating this Issue. I was unable duplicate the issue based on the following steps in the most recent release of HEDA: 1.50

1. Translation Workbench --> Translation Settings --> Add French Language and set to Active. **Note**: Active languages now show English and French.
2. Translation Workbench --> Translate: 
3. Language = French
4. Setup component = Record Type
5. Object = Course Connection
6. Set the value of Record Type Label Translation (Student) = Sophomore. **Note**: English value for Student = Freshman
7. Go to Language and timezone (under User Settings) and set the Language value to _français_
8. Created a new Contact: John Doe
9. Clicked the New button under the Course Connection on the Contact Record
10. The record type value I see for Student now shows Sophomore
11. I select a Course Offering ID and click Save
12. The Course Connection is saved to John Doe's Contact Record

Can you provide more detail on what you mean when you say the course connection is not saving?

**Comment by jacebryan** [comment]
@brds81 - If you've followed the steps above and are still having an issue with the Course Connection saving then please open up a Technical Support Case with Salesforce Support. Please use this [article ](https://powerofus.force.com/kA480000000L3t7?srPos=0&srKp=ka4&lang=en_US)to help guide you through this process.

**Comment by aligeez** [comment]
Closing due to inability to replicate issue.
