### ISSUE TITLE
new HEDA Trial org does not show "HEDA" as the Application Name

### ISSUE THREAD

**Issue by kevinswiggum** [SalesforceFoundation/HEDAP#580]
HEDA documentation shows the default App with the name "HEDA" as the app name. But if you create a new Trial org using the published trial template (e.g. a free trial org), the application name shows as "Lightning".

The HEDA managed package includes a default app named HEDA. This is a classic-version app that includes the HEDA related tabs. This app is included in the template. However, the template also includes a custom-built Lightning Console app named HEDA but with the label=Lightning. This app includes the ability to include LEX functionality (e.g. Utility bar). 

Since both apps configured in the template are named HEDA...the trial-engine is defaulting to the Lightning Console version rather than the packaged version. So the app name shows as Lightning instead of HEDA. Not a big deal, but inconsistent with documentation.

We just need to discuss how we want this configuration to change and update the template accordingly.

**Comment by kevinswiggum** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AE18XAAT" target="_blank">W-023616</a>

**Comment by ceiroa** [comment]
@kevinswiggum renamed the packaged app to HEDA (Classic) and renamed the lighting app as HEDA.
