### ISSUE TITLE
HEDA Settings Error when installed with NPSP

### ISSUE THREAD

**Issue by lparrott** [SalesforceFoundation/HEDAP#581]
Receiving an error in the page when NPSP and HEDA managed packages are installed together. The content doesn't load at all. Error: An internal server error has occurred Error ID: 346429827-100730 (319857279)

**Comment by lparrott** [comment]
lurch:add W-021154

**Comment by lparrott** [comment]
lurch:attach W-021154

**Comment by lparrott** [comment]
**lurch:attach W-021154

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000008n6hFAAQ" target="_blank">W-021154</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.53 (Beta 2)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.53
