### ISSUE TITLE
Investigate error when clicking checkboxes in HEDA setting page

### ISSUE THREAD

**Issue by xinnanlisf** [SalesforceFoundation/HEDAP#584]
We found an error when clicking checkboxes in HEDA setting page. This only happens in namespaced scratch org. In addition, the picklist of default account model is empty mostly due to it has no access to custom setting as well.

Steps to reproduce:
1. Spin up a scratch org
2. Go to HEDA settings -> system
3. Click any checkbox
4. The error shows up as below:

<img width="1184" alt="screen shot 2018-04-06 at 8 13 50 am" src="https://user-images.githubusercontent.com/28262573/38435208-f59f699e-399e-11e8-9713-4034cd4d4c39.png">

**Comment by mrbelvedere** [comment]
Included in beta release 1.53 (Beta 3)

**Comment by aligeez** [comment]
_Nice!_

**Comment by mrbelvedere** [comment]
Included in production release rel/1.53
