### ISSUE TITLE
Blank address record is created when a Contact is created w/out any Address Information

### ISSUE THREAD

**Issue by jacebryan** [SalesforceFoundation/HEDAP#588]
**Steps to reproduce:**

1. Go to the Contacts tab and click New
2. Enter a value in the First Name Field
3. Enter a value in the Last Name Field
4. Scroll down to the Address Information section
5. Select any value from Primary Address Type drop-down menu
6. Click Save

**Note**: We are also experiencing the same result when creating the address from the HH account.

**Outcome:**

Blank address record is created

**Comment by jacebryan** [comment]
See [W-023853]([url](https://foundation.lightning.force.com/one/one.app#/sObject/a2x8000000APXhvAAH/view))

**Comment by DavidOkner** [comment]
unable to reproduce for HH account / heda 1.51

STR
go to heda settings
click on account and contacts
enable Contact Multi-Addresses Enabled:
click on system tab
set default account model to HH account
set auto naming to first/last/household
within the UI click on contacts
click new
enter first/last and then scroll and enter a mailing address
click save
HH account is created
verify address record is created
go to account page layout
scroll down to contact related list click new
add first/last
click save
scroll down to address related list and verify that account level address has pushed down
go to account level 
scroll to the address related list
verify that only one address record has been created

**Comment by mrbelvedere** [comment]
Included in beta release 1.59 (Beta 1)

**Comment by mrbelvedere** [comment]
Included in production release 1.59
