### ISSUE TITLE
Exclude_from_Household_Name__c not working as expected

### ISSUE THREAD

**Issue by jacebryan** [SalesforceFoundation/HEDAP#591]
**Reported by: [Gonzalo Gómez de la Cal (S4G Consulting)](https://powerofus.force.com/_ui/core/userprofile/UserProfilePage?u=0058000000DlBsP&tab=sfdc.ProfilePlatformFeed)**

**Reported in this [Hub thread](https://powerofus.force.com/0D580000047y1d7)**

**Issue Identified:**

When "Exclude from Household Name" is checked on a Contact record that has been created from an existing Household the Household name is updated.

**Pre-configuration Steps**

1. Verify that the Default Account Model = Household Account
2. Verify that Automatic Household Naming = true (i.e. checked)

**Steps to reproduce Issue:**

1. Create a Contact: David Bowie
2. Confirm Bowie Household was created
3. Click on Bowie Household from David Bowie's Contact record
4. On the Related tab of the Bowie Household click Create under Contacts
5. Create a Contact: Robert Smith. **Note**: Be sure to check "Exclude from Household Name"

Notice from Robert Smith's Contact Record that the HH Account Name now shows "Bowie and Smith Household"

**Expected Outcome**

HH Account shows "Bowie Household" and NOT "Bowie and Smith Household"

**Comment by jacebryan** [comment]
**lurch: add

**Comment by jacebryan** [comment]
[W-024070](https://foundation.lightning.force.com/lightning/r/agf__ADM_Work__c/a2x8000000AVYRdAAP/view)

**Comment by ceiroa** [comment]
**lurch: attach W-024070

**Comment by mrbelvedere** [comment]
Included in beta release 1.67 (Beta 1)
