### ISSUE TITLE
HEDA Tech Debt: Refactor custom label references in HEDA setting page

### ISSUE THREAD

**Issue by xinnanlisf** [SalesforceFoundation/HEDAP#593]
We need to replace all $Label.hed.(LabelName) with $Label.c.(LabelName). 

We saw some issues regarding hed.(LabelName) recently in namespaced scratch orgs. Recently core team enhanced how custom label reference works in platform thus we can use c.(LabelName) to get custom labels directly. This also cleans up our code base and ensures consistency and maintainability.

**Comment by xinnanlisf** [comment]
**lurch:add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AVd0YAAT" target="_blank">W-024104</a>

**Comment by aligeez** [comment]
This issue was resolved on August 23, 2018.
