### ISSUE TITLE
Create global API classes for the UTIL classes in HEDA

### ISSUE THREAD

**Issue by lparrott** [SalesforceFoundation/HEDAP#594]
By creating global classes, this functionality doesn't need to be recreated in orgs with HEDA installed.

**Comment by lparrott** [comment]
**lurch: attach W-023827

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000APUMPAA5" target="_blank">W-023827</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.54 (Beta 2)

**Comment by mrbelvedere** [comment]
Included in production release rel/1.54
