### ISSUE TITLE
Better Error Handling - When Contact record is updated and they have 50+ relationships

### ISSUE THREAD

**Issue by aligeez** [SalesforceFoundation/HEDAP#602]
**Current Error Message --** 

> Error: Invalid Data. 
> Review all error messages below to correct your data.
> Apex trigger hed.TDTM_Contact caused an unexpected exception, contact your administrator: hed.TDTM_Contact: execution of AfterUpdate caused by: System.NullPointerException: Attempt to de-reference a null object: (hed)

**Steps to Replicate:** 

1. Create an org where the contacts have 50+ advisor/advisee relationship records 
2. Change (update) the 'Gender' for one of those contacts. 
3. Observe it hitting the REL_Relationships_Con_TDTM trigger handler and receive error (above)

- If the Contact is Updated and the Gender is changed 
- Find all Relationship records where the contact or the related contact is affected 
- All affected Relationship records will be reconciled to set the correct gender-specified type as defined in HEDA Settings.

So its going to go through all of the relationships this contact has and reconciling the relationships.

The data causing the issue may be messy and need to be cleaned up, but the error message could be better and point to the correct trigger handler at a minimum.

**Comment by ceiroa** [comment]
Do we have a source for this issue? Was it reported in the Hub?

**Comment by aligeez** [comment]
David Okner reported this to me from a Support Case he was working on. I reviewed it with Anne this morning and she said she's come across similar error messages that could be more clear.  We wanted to get this in the backlog to keep track of it. Not super urgent, but what I would consider a "perfective maintenance" item - Not really a bug, not really a feature enhancement, just polishing the edges.

**Comment by aligeez** [comment]
its the REL_Relationships_Con_TDTM trigger handler

if you look at the TDTM quip doc and search for gender you'll find:

**Comment by aligeez** [comment]
**lurch:add

**Comment by DavidOkner** [comment]
David Norman in Support said these cases had issues that weren't related to the error message: 18981989, 18782434

**Comment by aligeez** [comment]
***lurch: add*

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fQgcQAE" target="_blank">W-030679</a>

**Comment by kporray1** [comment]
This Issue is no longer being considered by the product team.
