### ISSUE TITLE
Recreation of course connection for primary faculty does not respect "Faculty Record Type Id"

### ISSUE THREAD

**Issue by wdci-dev** [SalesforceFoundation/HEDAP#605]
The logic of recreating course connection for primary faculty in COFF_Affiliation_TDTM line 133 does not respect the faculty recordtypeid defined in custom settings.

```
if (oldOff.Faculty__c == null && newOff.Faculty__c != null) {
 UTIL_Debug.debug('****Faculty member has been added to existing Course Offering');
 newFacultyIDs.add(newOff.Faculty__c);
 offsWithNewFaculty.add(newOff);
 // Do not perform adding new Course Enrollments if Course Connections is enabled.
 // Logic for if Course Connections is enabled is handled below.
 if (!UTIL_CustomSettingsFacade.courseConnectionsEnabled()) {
  Course_Enrollment__c enroll = new Course_Enrollment__c(Contact__c = newOff.Faculty__c,
   Account__c = newOff.Course__r.Account__c,
   Course_Offering__c = newOff.Id);
  courseEnrllsToInsert.add(enroll);
 }

 //Faculty member has been changed
 //   --> update Affiliation to Dpt to point it to the new Faculty
}
```

**Comment by kevinswiggum** [comment]
Hi @wdci-dev 
That particular section of code only runs if Course Connections is NOT enabled. Enabling Course Connections in HEDA settings goes hand-in-hand with mapping those record types (Faculty and Student)....so if the feature isn't enabled, HEDA assumes you're org is not enforcing those Record Types and doesn't include them during any auto-creation.

With Course Connections enabled, TDTM runs a different block of code that does respect the mapped record types.

Let me know if you are still seeing issues even with Course Connections enabled.

Thanks!

**Comment by wdci-dev** [comment]
Hi @kevinswiggum thanks for the explanation. Yes, I have enabled the course connection and defined the faculty record type in the HEDA settings. However this was not working until I defined the student record type. I realized that these 3 settings need to have value in order for the course connection created with correct record type.

But now I have a new issue where there are duplicated course connection created for the a course offering when a primary faculty is set. Is this intended?

**Comment by wdci-dev** [comment]
Hi @kevinswiggum my bad. I updated the custom setting manually with 15 character id instead of using the wizard. I have forced the update using HEDA Settings wizard again and it works fine. Thanks.

**Comment by jacebryan** [comment]
@wdci-dev - Are you OK if I close out this Issue? Sounds like you got things worked out on your end.

**Comment by wdci-dev** [comment]
@jacebryan sure.
