### ISSUE TITLE
Remove Errors tab from package

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#606]
We added an Errors tab in 1.55. It turns out that this makes the push upgrade fail for those that had already created a custom tab for that object (192 orgs). We'll have to remove the tab and create an out-of-cycle release to address this issue.

@xinnanlisf @aligeez @cdcarter

**Comment by ceiroa** [comment]
**lurch: add

**Comment by ceiroa** [comment]
This is doable, per https://success.salesforce.com/ideaView?id=08730000000GwCj.

**Comment by aligeez** [comment]
We resolved this issue on June 18, 2018.
