### ISSUE TITLE
Enable Reports checkbox on the Program Plan and Plan Requirements objects

### ISSUE THREAD

**Issue by jacebryan** [SalesforceFoundation/HEDAP#617]
Identified in HEDA Version 1.58
Found by: Jace Bryan

**Issue:**
You cannot create a report in HEDA for Program Plan or Plan Requirements unless you edit both objects and enable reports.

**Steps to reproduce:**

1. From the App Launcher search for "reports"
2. Click on the Report link that comes up in the Search results
3. Click on New Report (you will see the Choose Report Type box appear)
4. Enter "Plan" into the Search Report Types field

Results:

![image](https://user-images.githubusercontent.com/25934611/42711282-e0b97370-86ac-11e8-812c-ea9ddb22f431.png)

**Resolution:**
Enable Reports checkbox on both Objects.

1. Go to Setup
2. In Quick Find type in "Object Manager"
3. Click on "Object Manager" under Objects & Fields"
4. Enter "Program Plan" in Quick Find
5. Click Edit
6. Check the box for "Allow Reports"
7. Click Save.
8. Do the same thing for Plan Requirement.

**Comment by jacebryan** [comment]
**lurch: add

**Comment by jacebryan** [comment]
@ceiroa - When I look at another HEDA object I am seeing that "Allow Reports" is checked.

I am able to edit the Program Plans and Plan Requirements objects and check "Allow Reports" under Optional Features.

After doing so I am able to go to Reports --> New Report --> and search on "Plan". It does take a few minutes for the 7 report types to populate.

Before checking "Allow Reports" on both objects the Search results would return nothing. After checking "Allow Reports" on both objects the Search results now show these 7 report types:

![image](https://user-images.githubusercontent.com/25934611/42711049-22a2d728-86ac-11e8-9feb-3398860ff5b8.png)

**Comment by mrbelvedere** [comment]
Included in beta release 1.63 (Beta 2)

**Comment by mrbelvedere** [comment]
Included in production release 1.63
