### ISSUE TITLE
Erroneous Account renaming in ACCT_IndividualAccounts_TDTM

### ISSUE THREAD

**Issue by kevinswiggum** [SalesforceFoundation/HEDAP#621]
We received a question in the HUB where a user was seeing non-Household accounts getting renamed with Household naming logic whenever a new Contact was added to that account. In this case, they had an Account with *no recordtype* that existing before HEDA was installed. With HEDA installed, when they modified or added a Contact to that Account, the household name was applied. There are a number of vulnerabilities in the ACCT_IndividualAccounts_TDTM that can lead to this behavior.

**Contact On Delete Events:**
If an existing contact linked to an existing account is Deleted, line 115 of the trigger handler is checking if the account should be renamed. That if statement is ONLY checking if there is an account Id. It is _not_ checking if the Account is a household account. So the Account would be renamed for ALL (including blank) recordtypes. 

**AccountId is Cleared on an existing Contact:**
If the Account field on an existing contact is CLEARED (not modified to another account, just removed entirely), line 174 is checking if the originally linked Account should be renamed...but it is not checking if that Account is a Household account. So the Account would be renamed for ALL (including blank) recordtypes. 

**The Household record type (HH_Account) is deleted from the org (or never installed)**
It's possible that an org decides it doesn't need the Household record type and chooses to delete it. Or they may install HEDA directly from the package url (shown for each release) rather than use the installer. Many of the checks in the trigger handler are calling Util_Describe.getHhAccRecTypeID. That method looks at the available record types available on Account and returns the one where the developer name is HH_Account. If it does not find a RecordType with that name, the method returns null. So the comparison "if (c.Account.RecordTypeId == UTIL_Describe.getHhAccRecTypeID()) " is actually matching if the Account's RecordType is null. So Accounts with blank RecortTypeIds are treated as Households...and so are renamed when a linked Contact is edited or new Contact added. This is the exact scenario encountered by our Hub question. Ideally an additional check would see if the Account's RecordTypeId isn't blank (on lines 141 and 204).

**Potential for Hierarchy_Settings.Automatic_Household_Naming__c to be null**
A checkbox field can have 3 values: true, false and null. When a new field is added to to an existing custom settings object (or any object), that field is going to be Null for any existing records (not False). So the comparison "UTIL_CustomSettingsFacade.getSettings(). Automatic_Household_Naming__c != false" would succeed even if the actual value of the field is null instead of true). A better comparison would distinctly check for "== true" instead of != false. I'm not sure if this is actually happening in an org but noticed it as an additional vulnerability. The workaround in this case would just be to edit HEDA settings, uncheck "Automatic Household Naming" and click Save (this makes sure the value stored is actually False, not Null)

**Comment by kevinswiggum** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AYC3XAAX" target="_blank">W-026410</a>

**Comment by annejackson** [comment]
@kevinswiggum  are there any other ways to duplicate this issue besides:
1. Have an Account with no recordtype that existing before HEDA was installed. 
2. Install HEDA- what are their settings in heda settings?
3. Modify a Contact on that Account, the household name was applied. (was this with any field modified, or just last name?)
4. Add a Contact to that Account, the household name was applied.

**Comment by mrbelvedere** [comment]
Included in beta release 1.70 (Beta 2)

**Comment by mrbelvedere** [comment]
Included in production release 1.70
