### ISSUE TITLE
When the system automatically creates an Account for a Contact it should have the same name owner as the Contact

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#622]
Especially if the Contact.OwnerId is set to a value other than the current user.

This is related to this NPSP issue: https://github.com/SalesforceFoundation/Cumulus/issues/2577. Although in our case there is no importer.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AYC7VAAX" target="_blank">W-026461</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.60 (Beta 1)

**Comment by mrbelvedere** [comment]
Included in production release 1.60
