### ISSUE TITLE
Administrative account naming should be using setting

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#625]
The Administrative account record type is unmanaged, and thus we shouldn't be using it directly (or through the UTIL_Describe method) to apply the naming functionality. We need instead a setting similar to the one that lets a user tell us which record type they are using as Household.

There are a number of small issues related to this. List of all related issues identified:

1. We need new setting for users to tell us which record type is administrative
2. In the HEDA Settings UI, the new setting should be together with the one that lets users tell us which record type is household
3. The description for Household record type in the UI is outdated. It says "Account record type that  supports Household Addresses". It should also mention Household naming
4. The household and administrative account naming functionality should be pulling from the settings (one existing, one new). It shouldn't use the UTIL_Describe name. We should move the methods that retrieve account record types from UTIL_Describe into a test class to make it clear they should be used only from tests

**Comment by ceiroa** [comment]
**lurch: attach W-026197

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AYBnKAAX" target="_blank">W-026197</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.68 (Beta 3)

**Comment by mrbelvedere** [comment]
Included in production release 1.68
