### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#629]
To test whether we can lurch an item from one Github repo to a different project in AA.

**Comment by ceiroa** [comment]
**lurch: attach W-026871

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AYCgVAAX" target="_blank">W-026871</a>

**Comment by ceiroa** [comment]
Seems to be working! (Comment test)
