### ISSUE TITLE
Cannot Delete Triggers retrieving more records than necessary

### ISSUE THREAD

**Issue by j-brandolini** [SalesforceFoundation/HEDAP#635]
There exist triggers on Account, Contact, Program Plan, and Plan Requirement that block deletion of records if one or more records are present on key child objects.

Currently, the child queries are not bounded.  This means the more children that are present, the more they will retrieve.  This could impact a bulk deletion operation and/or have minor performance impact.

Recommend adding limit 1 to all subqueries in these triggers (see below for list of triggers) so that it never retrieves more than one child record per subquery, as that is enough to confirm the deletion cannot be allowed to proceed.

Trigger List:
* ACCT_CannotDelete_TDTM
* CON_CannotDelete_TDTM
* PPlan_CannotDelete_TDTM
* PReq_CannotDelete_TDTM

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007fN92AAE" target="_blank">W-027957</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.64 (Beta 2)

**Comment by mrbelvedere** [comment]
Included in production release 1.64
