### ISSUE TITLE
Recursion Flag stopping CON_Preferred_TDTM from working for batch sizes over 200

### ISSUE THREAD

**Issue by kevinswiggum** [SalesforceFoundation/HEDAP#639]
CON_Preferred_TDTM is one of the classes that was updated to address some of the static flag issues we saw with large batch sizes. However, the current code is still falling victim to the DML behavior where larger sets of records inserted/updated via DML are getting broken into 200 record chunks behind the scenes without resetting static variables. So CON_Preferred_TDTM will run for the first 200 records and then thinks it shouldn't run for the next set of 200.

Since this class runs before insert/update, the recursion check probably isn't necessary since it's just setting field values (email and phone) on the contact and not inserting/updating any other related records.

The current unit tests in TDTM_DMLgt200_TEST do not test the preferred email/phone functionality (i.e., do not assert the email and phone fields are getting set correctly on all records). I verified the bug with my own unit test:

`
@isTest
    static void insertUpdateContact() {
        List<Contact> testContacts = new List<Contact>();
        
        for (Integer i = 0; i < 300; i++) {
            Contact con = new Contact(
                FirstName='Test',
                LastName='Contact_forTests ' + i,
                hed__WorkEmail__c = 'junk@test.net',
                hed__Preferred_Email__c = 'Work',
                hed__WorkPhone__c = '206-777-8888',
                hed__PreferredPhone__c = 'Work');
            testContacts.add(con);
        }
        insert testContacts;
        
        List<Contact> insertedContacts = [Select FirstName, LastName, hed__WorkPhone__c, Phone, hed__WorkEmail__c, Email
                                          from Contact];
        
        for (Contact con : insertedContacts) {
            System.assertEquals(con.hed__WorkEmail__c, con.Email);
        }
        
    }`

Currently the workaround is to set batch size to 200 (not idea for large Bulk API updates) or manually set the Email and Phone values in the Bulk API import.

**Comment by kevinswiggum** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007fNF5AAM" target="_blank">W-028027</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.71 (Beta 2)

**Comment by mrbelvedere** [comment]
Included in production release 1.71
