### ISSUE TITLE
Contact Email address overwritten on create or update via API

### ISSUE THREAD

**Issue by natalyamurphyHE** [SalesforceFoundation/HEDAP#643]
When creating a Contact record via API and setting the standard Email field, it appears HEDA is overwriting that field with an org-wide default email address.

Steps to replicate:

1. Create an org-wide email address and assign it to your user profile
2. Open Developer Workbench and navigate to Data | Insert
3. Insert a Contact record, setting the standard Email field and, at a minimum, the LastName field
4. Save the record
5. Retrieve the record and note that the Email field now contains the org-wide email address

**Comment by aligeez** [comment]
@ceiroa @kevinswiggum - FYI
