### ISSUE TITLE
Add Custom Settings API, making some Custom Settings Facade functions global

### ISSUE THREAD

**Issue by lparrott** [SalesforceFoundation/HEDAP#648]
By making methods in the UTIL_CustomSettingsFacade class global in a new UTIL_CustomSettings_API class, customer orgs and other packages can access these methods.

**Comment by lparrott** [comment]
**lurch:attach: W-028715

**Comment by lparrott** [comment]
**lurch: attach W-028715

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007fO9DAAU" target="_blank">W-028715</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.64 (Beta 1)

**Comment by mrbelvedere** [comment]
Included in production release 1.64
