### ISSUE TITLE
Faculty contact getting duplicate Department affiliation records when inserting multiple Course Connections

### ISSUE THREAD

**Issue by kevinswiggum** [SalesforceFoundation/HEDAP#651]
This Power of Us Hub post started an investigation of Course Offerings (with Primary Faculty populated) creating multiple affiliation records linking a faculty contact to the same department.
https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000D6uj&fId=0D58000004Xrgok

If you insert a Course Offering with primary faculty (or a Faculty course connection), HEDA will check their existing affiliation records to see if that contact is already linked to the course's department. If they are not, HEDA will create the affiliation. That works fine for single-record transactions. 

However, if you insert multiple course offerings that relate that faculty member to the department (e.g., two course offerings in the same department) within the same transaction (data loader, integration, etc), HEDA is adding the new department affiliation to the "list to be inserted" without checking if there's already another affiliation linking the same affiliation to the same contact in that list. That causes the affiliation to get created multiple times.

The affected code is found in CCON_Faculty_TDTM when affiliationsToInsert list gets populated (before insert section).

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007fOT3AAM" target="_blank">W-028957</a>

**Comment by jacebryan** [comment]
This issue was reviewed by the HEDA team and marked as a solid candidate for a Community Contribution. Please comment with any questions or concerns you may have. Thank you!

**Comment by mrbelvedere** [comment]
Included in beta release 1.70 (Beta 8)

**Comment by mrbelvedere** [comment]
Included in production release 1.70
