### ISSUE TITLE
HEDA objects in setup menu are impossible to distinguish from other objects with the same name

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#654]
We should consider renaming all the HEDA objects for easy differentiation.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007fOYrAAM" target="_blank">W-029023</a>

**Comment by annejackson** [comment]
Screenshots @aligeez fyi
![multiple custom objects named the same_2](https://user-images.githubusercontent.com/35311289/46696667-acfa5580-cbe0-11e8-8195-cdf5bc06c053.png)
![multiple custom objects named the same](https://user-images.githubusercontent.com/35311289/46696668-acfa5580-cbe0-11e8-907a-4f8031314788.png)

**Comment by ceiroa** [comment]
Changing the label names in the objects won't be an acceptable solution, as it changes the tab names as well.
