### ISSUE TITLE
HEDA Tech Debt: Migrate Program Plan Before Insert/Before Update Trigger functionality to After Insert/After Update Trigger functionality

### ISSUE THREAD

**Issue by jbrandolinisf** [SalesforceFoundation/HEDAP#660]
Migrate Program Plan Before Insert/Before Update Trigger functionality to After Insert/After Update Trigger functionality:

- Move logic to mark other plan records associated with same account non primary from Before Insert / Before Update to After Insert / After Update. _Best practice is to update same records in Before Insert/Update trigger context, and other records in After Insert/Update context.  Since this trigger updates other records, it should do this in an "After" context_
- Update Trigger Default Config to reflect existence of After Update, After Insert for PPlan_Primary_TDTM trigger, remove Before Insert, Before Update records from default configuration
- Define Register Trigger values for the new trigger combinations (PPlan_Primary_TTDM_AfterInsert, AfterUpdate)

**Comment by jbrandolinisf** [comment]
**lurch: add

**Comment by jbrandolinisf** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fPKgQAM" target="_blank">W-029599</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fPKlQAM" target="_blank">W-029600</a>

**Comment by ceiroa** [comment]
It looks like there was some issue here, @jbrandolinisf, and two items got created on the AA side. You'll probably want to delete one of them...

**Comment by jbrandolinisf** [comment]
I deleted and re-added the lurch tag, not realizing it had picked it up.  I will delete the duplicate...

**Comment by mrbelvedere** [comment]
Included in beta release 1.65 (Beta 1)

**Comment by mrbelvedere** [comment]
Included in production release 1.65
