### ISSUE TITLE
On HEDA Setting page, record type validation checkbox has wrong class name and id

### ISSUE THREAD

**Issue by xinnanlisf** [SalesforceFoundation/HEDAP#684]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the HEDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
Bug
* **What is the current behavior?**
"Enable Record Type Validation" has wrong class name/id:  "store-errors"
* **What is the expected behavior?**
"Enable Record Type Validation" should be using class name/id: "affiliation-record-type-enforced"
* **What is the motivation / use case for changing the behavior?**
For consistency and accuracy of browser test.
Back-end cleanup item, will have no significant front-end impact to users or orgs. 
* **Acceptance Criteria**
N/A

* **Keyboard Acceptance Criteria**

N/A

* **Screenreader Acceptance Criteria**

N/A

**Comment by aligeez** [comment]
***lurch: add*

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fQhkQAE" target="_blank">W-030693</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.68 (Beta 1)

**Comment by mrbelvedere** [comment]
Included in production release 1.68
