### ISSUE TITLE
Creation of new Objects (Language & Contact Language) & fields to support Languages in HEDA

### ISSUE THREAD

**Issue by robertbwatson** [SalesforceFoundation/HEDAP#715]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the HEDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**

Feature

* **What is the current behavior?**

The current functionality does not exist in HEDA.

* **What is the expected behavior?**

This issue will result in new objects & fields and not any new logic/functionality. The user will interact with these objects the same way they interact with other objects in Salesforce.

A user can navigate to a Contact record to view or set their preferred language. There may be other languages that the Contact can speak that will also be tied to that Contact, as well as their proficiency in those languages.

* **What is the motivation / use case for changing the behavior?**

These new objects & fields will allow an organization to track what languages are spoken by students/staff/parents, their fluency with each, and where they are spoken. 

The language record will track the preferred (primary) language of a Contact in HEDA. The ability for an educational institution to know that Student John's primary language is English, but the best way to communicate with his parents' is Spanish. The ability to know the fluency of an instructor's languages in a global institution being taught in multiple countries or countries with more than one language; e.g. Belgium with Flemmish and French.

**Comment by robertbwatson** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007x7KjQAI" target="_blank">W-031371</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.72 (Beta 6)

**Comment by mrbelvedere** [comment]
Included in production release 1.72
