### ISSUE TITLE
Creation of new Facility object & fields to support Facilities in HEDA

### ISSUE THREAD

**Issue by robertbwatson** [SalesforceFoundation/HEDAP#716]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the HEDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**

Feature

* **What is the current behavior?**

The current functionality does not exist in HEDA.

* **What is the expected behavior?**

This issue will result in new objects & fields and not any new logic/functionality. The user will interact with this object the same way they interact with other objects in Salesforce.

A user can navigate to a Course Offering record and see where the Couse Offering is being held. A user can manage various facilities in the educational institution.

* **What is the motivation / use case for changing the behavior?**

Short of providing full-on Facility management, this allows an educational organization to house information with respect to where classes are being held and other school property assets. This could be a classroom location, a campus location, location of a lecture hall, location of a laboratory, or simply locations for campus buildings that don't necessarily pertain to student activity, e.g. Maintenance/IT Facilities. 

1.) A Facility will look up to Account, e.g. "Department of Computer Science" account could have 3 "Locations" that are Building A, Building B, Building C, and Building A has child "Locations" that are Lecture Hall 121, Lecture Hall 131" - ex: Building A in this story would be something like "The Walter Smith Sciences Building" 

2.) Course Offerings would look up to Facility. For example, Course Offering "Biology 101 - Spring 2019 - Taught by Professor Smith" would be offered in the location of Lecture Hall 121 > Building A

**Comment by robertbwatson** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007x7KoQAI" target="_blank">W-031372</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.73 (Beta 2)

**Comment by mrbelvedere** [comment]
Included in production release 1.73
