### ISSUE TITLE
HEDA Idea: Program Offering

### ISSUE THREAD

**Issue by wdci-dev** [SalesforceFoundation/HEDAP#719]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the HEDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
Currently, we are not able to track the programs that we offer in the 1st Intake vs 2nd Intake in the same calendar year.

* **What is the expected behavior?**
Maybe HEDA could have something similar to course offering for program in order for us to track program available for each intake.

**Comment by aligeez** [comment]
@wdci-dev  - Thank you for your enhancement idea, but before we can get it in the GitHub queue we need to make sure it's posted on the Power of Us Ideas page - https://powerofus.force.com/hub-ideas.  Can you please submit your idea there and please include as many more use-cases (more details the better!) that you can think of?  This will also allow some time for other education institutions to iterate and provide their uses-cases. Once it has been fully fleshed out me (HEDA Product Manager) and other members of my team review the ideas to pull the top requested ones into our backlog (That's when it would come into GitHub).  I will be closing this work item in the meantime, but feel free to post any questions or comments you may have and @Mention me. Thank you!
