### ISSUE TITLE
Facility Naming: Include a "Display Name" formula field on the Facility that includes the Account name or Parent Facility name

### ISSUE THREAD

**Issue by robertbwatson** [SalesforceFoundation/HEDAP#720]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the HEDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
After #716 is delivered, a user must manually name a Facility record. There could be many "Room 201" records.

* **What is the expected behavior?**
By adding a new "Display Name" unmanaged formula field on to the Facility object, the Facility record can have a name displayed that incorporates the Account Name or Parent Facility Name. (For example, "Thomas Edison Building - Room 201".)

The user will be able to update this formula field if they want to choose a different format to use.

* **What is the motivation / use case for changing the behavior?**
Having 10 "Room 201" records with no friendly name will make it difficult for a user to know which record to choose.

* **Acceptance Criteria**

  - **Given**: I create a new Facility record with the name "Room 201" and associate it to the "Thomas Edison Building" Parent Facility
  - **When**: I save the record
  -  **Then**: The "Display Name" field on the record will display "Thomas Edison Building - Room 201"

* **Acceptance Criteria**

  - **Given**: I create a new Facility record with the name "Room 201" and associate it to the "College of Business" Account
  - **When**: I save the record
  -  **Then**: The "Display Name" field on the record will display "College of Business - Room 201"

* **Acceptance Criteria**

  - **Given**: I create a new Facility record with the name "Room 201" and associate it to the "Thomas Edison Building" Parent Facility and "College of Business" Account
  - **When**: I save the record
  -  **Then**: The "Display Name" field on the record will display "Thomas Edison Building - Room 201" (the Parent Facility is used when both Account and Parent Facility are specified)

**Comment by robertbwatson** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000008Ll4hQAC" target="_blank">W-031480</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.73 (Beta 6)

**Comment by mrbelvedere** [comment]
Included in production release 1.73
