### ISSUE TITLE
Enhancement: Do not update the Affiliation status to Former when there other Program Enrollment records attached

### ISSUE THREAD

**Issue by aligeez** [SalesforceFoundation/HEDAP#730]
When deleting a Program Enrollment, if its related Affiliation's Status is updated (instead of the Affiliation being deleted), the Status is now updated only if the Affiliation isn't related to any other existing Program Enrollment records. In other words, if "Delete Related Affiliation When Deleting Program Enrollment" is disabled in HEDA Settings | Affiliations | Settings, the value in "Status Specified for Affiliation Not Deleted" does not apply unless the related Affiliation has no other Program Enrollments related to it.

* **Acceptance Criteria**

- Ensure that the "Delete Related Affiliation When Deleting Program Enrollment" setting is false.
- Create a Program Enrollment for a Contact.
- Go to the Program Enrollment Affiliation record that was automatically created.
- On the Program Enrollment related list, create another Program Enrollment (into the same Program) for the Affiliation.
- Delete the Program Enrollment record. The Program Enrollment record will be deleted, but the Affiliation record (& the other Program Enrollment record) will still exist. The Affiliation's Status will NOT be updated to the "Status of Affiliation Related to Deleted Program Enrollment" setting.
- Delete the remaining Program Enrollment record. The Affiliation's Status will be updated to the "Status of Affiliation Related to Deleted Program Enrollment" setting.

**Comment by aligeez** [comment]
**lurch: attach W-031068

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007fRCEQA2" target="_blank">W-031068</a>

**Comment by mrbelvedere** [comment]
Included in production release 1.71
