### ISSUE TITLE
New HEDA Object: Term Grades

### ISSUE THREAD

**Issue by JasonFitzy** [SalesforceFoundation/HEDAP#738]
**New Object in HEDA Framework**: The purpose of this new object is to allow institutions to record grades for students in a given course offering during a particular term and across terms. It is not intended to be used for grading an assignment or quiz, but recording a final grade, or a progress report grade, or recording of a grade for an institutionally defined grading period.

* **What is the motivation / use case for changing the behavior?**
In our effort to support P-20 lifelong learning/education commitment.

* **Acceptance Criteria**

- As an admin I can log into my HEDA org and see the new object "Term Grades"
- As an admin I can see the necessary fields included in  "Term Grades" (see quip doc for specifics)

**Comment by JasonFitzy** [comment]
**lurch: add

**Comment by JasonFitzy** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000008LlU1QAK" target="_blank">W-031796</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000008LlUBQA0" target="_blank">W-031798</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.74 (Beta 3)

**Comment by mrbelvedere** [comment]
Included in production release 1.74
