### ISSUE TITLE
Language: Contact "Primary Language" Automatic Population

### ISSUE THREAD

**Issue by robertbwatson** [SalesforceFoundation/HEDAP#741]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
When a new Contact Language record is marked as the Primary Language for that Contact, the Primary Language lookup field on the Contact does NOT get populated.

* **What is the expected behavior?**
When a new Contact Language record is marked as the Primary Language for the Contact, the Primary Language lookup field on the Contact should be automatically populated with the Language record.

* **What is the motivation / use case for changing the behavior?**
By automatically setting the lookup field, the user can easily see the primary language for that Contact without having to go to the related list.

* **Acceptance Criteria**

  - **Given**: I set the Primary Language checkbox on the Contact Language record
  - **When**: I save the Contact Language record
  - **Then**: The Primary Language lookup on the related Contact should be set to the Language record

* **Acceptance Criteria**

  - **Given**: I unset the Primary Language checkbox on the Contact Language record
  - **When**: I save the Contact Language record
  - **Then**: The Primary Language lookup on the related Contact should be cleared

* **Acceptance Criteria**

  - **Given**: I set the Primary Language checkbox on the Contact Language record and there's an existing Contact Language record already set as the Primary Language
  - **When**: I save the Contact Language record
  - **Then**: The other Contact Language record should be unset as the Primary Language, and the Primary Language lookup on the related Contact should be set to the new Language record

* **Acceptance Criteria**

  - **Given**: There's an existing Contact Language record that is set as the Primary Language
  - **When**: I delete the Contact Language record
  - **Then**: The Primary Language lookup on the related Contact should be cleared

**Comment by robertbwatson** [comment]
@aligeez  @JasonFitzy  Can one of you review this (specifically the acceptance criteria) before I lurch this?

**Comment by JasonFitzy** [comment]
Reviewed and discussed with Bobby. Two ACs added based on discussion around Primary Language lookup field on the Contact page. All set and great work as always!

**Comment by robertbwatson** [comment]
@JasonFitzy Unfortunately I had to remove the two ACs we just added since we've now discussed that the lookup field is actually a lookup to the Language and not a reciprocal to the Contact Language record. But I think this makes things much cleaner now! Going to lurch in a moment.

**Comment by robertbwatson** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000008LlYrQAK" target="_blank">W-031856</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.74 (Beta 2)

**Comment by mrbelvedere** [comment]
Included in production release 1.74
