### ISSUE TITLE
Language: Contact "Primary Language" Updates Contact Language Record

### ISSUE THREAD

**Issue by robertbwatson** [SalesforceFoundation/HEDAP#746]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
With the release of #741, the Contact's "Primary Language" field is automatically updated when a Contact Language record is marked as the Primary Language.

However, a user can decide to update this lookup on the Contact at any time. Nothing currently happens when the Primary Language lookup field on the Contact is updated.

* **What is the expected behavior?**
If a user updates the Primary Language lookup on the Contact, the system should search for an existing Contact Language record for that Language and set it as the Primary Language. If a record doesn't already exist, a record should be created.

* **What is the motivation / use case for changing the behavior?**
We have automation for setting this lookup field when the user creates or modifies a Contact Language record, but not the other way around.

"As an Admin, when I set the Primary Language field on a contact, it should create a Contact Language record for the contact and mark it as primary if it doesn't already exist."

* **Acceptance Criteria**

  - **Given**: I have an "English" Language record and am updating a Contact record
  - **When**: I set the Contact's Primary Language lookup to "English"
  - **Then**: The system will search for an existing Contact Language record for the given Contact/Language. Since one does not exist, it will create a new Contact Language record with Fluency set to the default value and Primary Language checked.

* **Acceptance Criteria**

  - **Given**: I have an "English" Language record and am updating a Contact record. The Contact already has an "English" Contact Language record, but it is not set as the contact's Primary Language.
  - **When**: I set the Contact's Primary Language lookup to "English"
  - **Then**: The system will search for an existing Contact Language record for the given Contact/Language. It finds the existing record and checks the Primary Language checkbox.

* **Acceptance Criteria**

  - **Given**: I have an "English" Language record and am updating a Contact record. The Contact's Primary Language is currently set to "French".
  - **When**: I set the Contact's Primary Language lookup to "English"
  - **Then**: In addition to searching for an existing "English" Contact Language record and setting the Primary Language checkbox to true, the system also updates the "French" Contact Language record to no longer have the Primary Language checkbox checked.

**Comment by aligeez** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000008LljBQAS" target="_blank">W-031985</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.75 (Beta 2)

**Comment by mrbelvedere** [comment]
Included in production release 1.75
