### ISSUE TITLE
Language: Do not allow deletion of a Language record if there are Contact Language records associated to it

### ISSUE THREAD

**Issue by robertbwatson** [SalesforceFoundation/HEDAP#748]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
A Language record can be deleted. If there are Contact Language records associated to it, the Language lookup field is simply cleared.

* **What is the expected behavior?**
A friendly error should be shown telling the user that the Language record cannot be deleted.
An admin cannot create a Contact Language record that does not lookup to a Language. In other words, "Language" is a required field on "Contact Language" 

* **What is the motivation / use case for changing the behavior?**
Deleting a Language record when there are Contact Language records still associated to it will lead to data loss in the customer org.

* **Acceptance Criteria**

  - **Given**: There's a Language record with one or multiple Contact Language records associated to it
  - **When**: I attempt to delete that Language record
  - **Then**: A friendly error telling me that the Language record cannot be deleted should appear.

**Comment by aligeez** [comment]
**Lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000008LlhtQAC" target="_blank">W-031969</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.73 (Beta 5)

**Comment by mrbelvedere** [comment]
Included in production release 1.73
