### ISSUE TITLE
Update API version of all files to v45.0

### ISSUE THREAD

**Issue by xinnanlisf** [SalesforceFoundation/HEDAP#749]
* **Do you want to request a *feature* or report a *bug*?**
Feature
* **What is the current behavior?**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**
We need to update HEDA api version to the latest.

**Comment by xinnanlisf** [comment]
@aligeez just created this github issue for api version. Let me know if it looks good to you. Feel free to make any change for sure. I will connect it to the item we already have later.

**Comment by aligeez** [comment]
**Lurch: add

@xinnanlisf  good to go.

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000008LljLQAS" target="_blank">W-031987</a>

**Comment by xinnanlisf** [comment]
**Lurch: connect W-010358

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003nhnSAAQ" target="_blank">W-010358</a>

**Comment by mrbelvedere** [comment]
Included in beta release 1.72 (Beta 6)

**Comment by mrbelvedere** [comment]
Included in production release 1.72

**Comment by robertbwatson** [comment]
@xinnanlisf Since this was attached after the merge, I don't think it was closed properly. I think it can be closed now?
